<pre class='metadata'>
Title: DCAT-AP-LT
Shortname: DCAT-AP-LT
Level: 1
Status: LD
Repository: ivpk/DCAT-AP-LT
URL: https://ivpk.github.io/DCAT-AP-LT/
Editor: IVPK, https://ivpk.lrv.lt/lt/
Abstract: DCAT-AP-LT metaduomenų modelis.
Complain About: accidental-2119 yes, missing-example-ids yes
Markup Shorthands: markdown yes, css no
Translation: en en/index.html
Boilerplate: copyright no, spec-metadata no, abstract no, conformance no
</pre>

# Įžanga

<dl>
    <dd>DCAT-AP-LT yra metaduomenų specifikacija, skirta Lietuvos duomenų rinkiniams ir paslaugoms aprašyti. DCAT-AP-LT yra Europos metaduomenų specifikacijos DCAT-AP plėtinys, parengtas vadovaujantis DCAT-AP specifikacijos formavimui nustatytomis taisyklėmis ir rekomendacijomis, įtraukiant ontologijas ir tezaurus kaip pagalbines priemones aprašant duomenis.

DCAT-AP-LT apima BREG-DCAT-AP(https://github.com/SEMICeu/BregDCAT-AP/tree/main/releases/2.1.0) naudojamas klases ir papildo jas Informacinės Sistemos klase išplečiančia dcat:Catalog klasę bei dvejais kontroliuojamais žodynais Informacinės sistemos tipui ir svarbai pažymėti pagal Valstybės informacinių išteklių valdymo įstatyme  nustatytą  tvarką.

</dd>
</dl>
## Kontekstas

Šiuo metu numatoma, jog Europos Komisija teiks paramą šioms [Europos bendroms duomenų erdvėms](https://digital-strategy.ec.europa.eu/en/policies/data-spaces) kurti:
<ul>
<li>Žemės ūkio;  </li>
<li> Kultūrinio paveldo; </li>
 <li>Energetikos; </li>
<li>Finansinių; </li>
<li> Žaliojo kurso; </li>
<li>Kalbos; </li>
 <li>Sveikatos; </li>
<li> Pramonės (gamybos); </li>
<li>Žiniasklaidos </li>
 <li>Judumo; </li>
 <li>Viešojo administravimo;  </li>
<li>Mokslinių tyrimų ir inovacijų; </li>
 <li>Su įgūdžiais susijusių;  </li>
<li>Turizmo.  </li>
</ul>


Ši specifikacija turi palaikyti šias planuojamas duomenų erdves ir užtikrinti lengvesnį duomenų valdymą jose.  Realizavus šią specifikaciją informacinėje sistemoje, kur bus kataloguojami Lietuvos Respublikos registrų ir kitų informacinių sistemų duomenys - bus sukuriamos priemonės, padedančios Lietuvos duomenų valdymo sričių įgaliotiniams kurti registrų ir kitų informacinių sistemų duomenų valdymo strategijas, atpažinti netikslingą informacijos dubliavimą, taip pat suteiks galimybę dalintis Lietuvos Respublikos duomenimis su Europos Sąjunga pagal bendrą semantinį modelį.



## Aprėptis

Šis specifikacija yra orientuota į Valstybės informacinių išteklių valdymo įstatymo nuostatų dėl informacinėse sistemose tvarkomų metaduomenų įgyvendinimo.

# Statusas

DCAT-AP-LT 0.1 

# Licencija

Šio modelio medžiaga skelbiama pagal CC-BY 4.0 licenciją, nebent pažymėta kitaip.

# Terminologija

<table>
    <tr>
        <th>Trumpinys (en. prefix)</th>
        <th>Vardų erdvės URI</th>
    </tr>
 <tr>
        <td>
		<code>dcataplt</code>
	</td>
        <td>
		<code>https://data.gov.lt/onto/DCATAPLT#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>adms</code>
	</td>
        <td>
		<code>http://www.w3.org/ns/adms#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>cpsv</code>
	</td>
        <td>
		<code>http://purl.org/vocab/cpsv#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>cv</code>
	</td>
        <td>
		<code>http://data.europa.eu/m8g/</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>dcat</code>
	</td>
        <td>
		<code>http://www.w3.org/ns/dcat#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>dqv</code>
	</td>
        <td>
		<code>http://www.w3.org/ns/dqv#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>eli</code>
	</td>
        <td>
		<code>http://data.europa.eu/eli/ontology#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>foaf</code>
	</td>
        <td>
		<code>http://xmlns.com/foaf/0.1/</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>odrl</code>
	</td>
        <td>
		<code>http://www.w3.org/ns/odrl/2/</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>prov</code>
	</td>
        <td>
		<code>http://www.w3.org/ns/prov#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>rdfs</code>
	</td>
        <td>
		<code>http://www.w3.org/2000/01/rdf-schema#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>skos</code>
	</td>
        <td>
		<code>http://www.w3.org/2004/02/skos/core#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>spdx</code>
	</td>
        <td>
		<code>http://spdx.org/rdf/terms#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>vann</code>
	</td>
        <td>
		<code>http://purl.org/vocab/vann/</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>vcard</code>
	</td>
        <td>
		<code>http://www.w3.org/2006/vcard/ns#</code>
	</td>
    </tr>
    <tr>
        <td>
		<code>voaf</code>
	</td>
        <td>
		<code>http://purl.org/vocommons/voaf#</code>
	</td>
    </tr>
</table>


# Modelio apžvalga

DCAT-AP-LT apima visas BREG-DCAT-AP 2.1 nudojamas klases ir papildo jas Informacinės Sistemos klase išplečiančia dcat:Catalog klasę bei dvejais kontroliuojamais žodynais Informacinės sistemos tipui ir svarbai pažymėti taip, kaip apibrėžiama Valstybės informacinių išteklių valymo įstatyme.
Taip pat, didelės vertės duomenų rinkinių metaduomenims aprašyti naudojamas DCAT-AP-HVD klases ir papildomas savybes.

<img src="uml.png" width="800px" height="454px">



# Klasės

## Informacinė Sistema (dcataplt:InformationSystem)

<dl>
    <dt>Apibrėžimas</dt>
    <dd>Programinės įrangos visuma valstybės ar savivaldybės institucijos ar įstaigos, kito viešojo administravimo subjekto, viešosios įstaigos ar valstybės valdomos įmonės veiklos procesams skaitmenizuoti, duomenims tvarkyti ir (ar) administracinėms ar viešosioms paslaugoms teikti elektroniniu būdu.</dd>
    <dt>Savybės</dt>
    <dd>
        <table class="data-table simple">
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:12%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:6%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:27%">Apibrėžimas</th>
                <th class="data-table__header-title--sortable" style="width:27%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:6%">Perpanaudojimas</th>
            </tr>
<br></br>
            <tr class="data-table__header">
                <td>[dcataplt:importance](http://data.gov.lt/onto/DCATAPLT#)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>1..1</td>
                <td>Informacinės sistemos svarba.</td>
                <td>Informacinės sistemos svarba pagal Valstybės informacinių išeklių valdymo įstatymo reikalavimus.</td>
                <td>P</td>
            </tr>
            <tr class="data-table__header">
                <td>[dcataplt:type](http://data.gov.lt/onto/DCATAPLT#)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>1..1</td>
                <td>Informacinės sistemos tipas.</td>
                <td>Informacinės sistemos tipas pagal Valstybės informacinių išeklių valdymo įstatymo reikalavimus.</td>
                <td>P</td>
            </tr>
            <tr class="data-table__header">
                <td>[dcataplt:ISImportanceAssessmentURL](http://data.gov.lt/onto/DCATAPLT#)</td>
                <td>[rdfs:Resource](http://www.w3.org/2000/01/rdf-schema#Resource)</td>
                <td>1..1</td>
                <td>Informacinės sistemos svarbos vertinimas.</td>
                <td>URL nuoroda į informacinės sistemos svarbos vertinimo dokumentą.</td>
                <td>P</td>
            </tr>
        </table>
    </dd>
</dl>

# Kontroliuojami žodynai

## Svarba (dcataplt:Importance)

<dl>
    <dt>Apibrėžimas</dt>
    <dd>Informacinės sistemos svarba pagal Valstybės informacinių išeklių valdymo įstatymo reikalavimus.</dd>
    <dt>Galimų svarbos lygmenų sąrašas</dt>
    <dd>
        <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:10%">Reikšmė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Range</th>
                <th class="data-table__header-title--sortable" style="width:50%">Reikšmės aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
            <tr class="data-table__header">
                <td>[Ypatingos svarbos](http://data.gov.lt/onto/DCATAPLT#)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>Ypatingos svarbos valstybės informaciniai ištekliai – jiems priskiriamos informacinės sistemos, kuriose esančių duomenų prieinamumo, vientisumo ir konfidencialumo pažeidimo poveikis sukelia padarinius visai valstybei (poveikis daugiau negu 5 apskrityse, daugiau negu 50 procentų gyventojų ar institucijų).</td>  
                <td>P</td>
            </tr>
            <tr class="data-table__header">
                <td>[Svarbūs](http://data.gov.lt/onto/DCATAPLT#)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>Svarbūs valstybės informaciniai ištekliai – jiems priskiriamos informacinės sistemos, kuriose esančių duomenų prieinamumo, vientisumo ir konfidencialumo pažeidimo poveikis sukelia padarinius didelei valstybės, institucijų ir gyventojų daliai (poveikis 2–5 apskrityse, 6–50 procentų gyventojų ar institucijų).</td>      
                <td>P</td>
            </tr>
            <tr class="data-table__header">
                <td>[Vidutinės svarbos](http://data.gov.lt/onto/DCATAPLT#t)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>Vidutinės svarbos valstybės informaciniai ištekliai – jiems priskiriamos informacinės sistemos, kuriose esančių duomenų prieinamumo, vientisumo ir konfidencialumo pažeidimo poveikis sukelia padarinius nedidelei valstybės, institucijų ir gyventojų daliai (poveikis keliose vienos apskrities savivaldybėse, 1–5 procentų gyventojų ar institucijų).</td>      
                <td>P</td>
            </tr>
            <tr class="data-table__header">
                <td>[Mažos svarbos](http://data.gov.lt/onto/DCATAPLT#)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>Mažos svarbos valstybės informaciniai ištekliai – jiems priskiriamos informacinės sistemos, kuriose esančių duomenų prieinamumo, vientisumo ir konfidencialumo pažeidimo poveikis sukelia padarinius pavienėms institucijoms ar pavieniams fiziniams asmenims (poveikis ne daugiau kaip vienos apskrities savivaldybei, iki 1 procento gyventojų ar institucijų).</td>      
                <td>P</td>
            </tr>
        </table>
    </dd>
</dl>

## Tipas (dcataplt:Type)

<dl>
    <dt>Apibrėžimas</dt>
    <dd>Informacinės sistemos tipas pagal Valstybės informacinių išeklių valdymo įstatymo reikalavimus.</dd>
    <dt>Galimų informacinių sistemų tipų sąrašas</dt>
    <dd>
        <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:10%">Reikšmė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Range</th>
                <th class="data-table__header-title--sortable" style="width:50%">Reikšmės aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
                <td>-</td>
            </tr>
<br></br>
            <tr class="data-table__header">
                <td>[Registro informacinė sistema](http://data.gov.lt/onto/DCATAPLT#)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>Registrų informacinės sistemos, kuriose registruojami objektai, tvarkomi objektų ir jų registravimo duomenys.</td>
                <td>P</td>
            </tr>
            <tr class="data-table__header">
                <td>[Valstybės informacinė sistema](http://data.gov.lt/onto/DCATAPLT#)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>Valstybės informacinės sistemos, kuriose tvarkomi subjektų teisės aktuose nustatytoms funkcijoms atlikti reikalingi duomenys, įskaitant ir valstybės informacines sistemas, skirtas kelių ar daugelio subjektų jų veiklą reglamentuojančiuose teisės aktuose nustatytoms vienodo pobūdžio veiklos funkcijoms atlikti ir duomenims tvarkyti.</td>      
                <td>P</td>
            </tr>
            <tr class="data-table__header">
                <td>[Vidaus administravimo informacinė sistema](http://data.gov.lt/onto/DCATAPLT#)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>Vidaus administravimo informacinės sistemos, kuriose tvarkomi subjektų valdomi duomenys, reikalingi vidaus administravimo funkcijoms ar kitoms pagalbinio pobūdžio funkcijoms, kurios padeda įgyvendinti subjektui teisės aktuose nustatytus uždavinius.</td>    
                <td>P</td>
            </tr>
        </table>
    </dd>
</dl>


# Naudojamos BregDCAT-AP klasės ir savybės


## Katalogas

<dl>
    <dt>Apibrėžimas</dt>
    <dd>Katalogas arba saugykla, kurioje saugomi aprašomi duomenų rinkiniai arba duomenų paslaugos.</dd>
    <dd>
 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:15%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:30%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:30%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:15%">Intervalas</th>
            </tr>
            <tr class="data-table__header">
                <td>[Katalogas](http://www.w3.org/ns/dcat#Catalog)</td>
                <td>Katalogas arba saugykla, kurioje saugomi aprašomi duomenų rinkiniai arba duomenų paslaugos.</td>
                <td>Šia klase apibūdinama konkreti informacinė sistema – valstybės informacinė sistema ar registras, kurio apimtyje yra tvarkomi duomenų rinkiniai.</td>
                <td>[dcat:Catalog](http://www.w3.org/ns/dcat#Catalog)</td>
            </tr>
 </table>
<br>
<table class="data-table simple">
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:35%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
            <tr class="data-table__header">
                <td>Aprašymas</td>
                <td>[dct:description](http://purl.org/dc/terms/description)</td>
                <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
                <td>1..n</td>
                <td>Šia savybe rekomenduojama pateikti trumpą informacinės sistemos paskirties aprašymą, kaip pateikiama informacinės sistemos nuostatuose.</td>
                <td>Šioje savybėje pateikiamas katalogo laisvo teksto aprašas laisvos formos tekstu. Šią savybę galima pateikti keliomis kalbomis.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_description">E</a></td>
            </tr>
                <!-- Trūko identifier -->	
			          <tr class="data-table__header">
                <td>Identifikatorius</td>
                <td>[dct:identifier](http://purl.org/dc/terms/identifier)</td>
                <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
                <td>1..1</td>
                <td>-</td>
                <td>Šioje savybėje nurodomas katalogo identifikatorius.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_identifier">E</a></td>
                </tr>
            <tr class="data-table__header">
                <td>Skelbėjas</td>
                <td>[dct:publisher](https://w3c.github.io/dxwg/dcat/#Property:resource_publisher)</td>
                <td>[foaf:Agent](http://xmlns.com/foaf/0.1/Agent)</td>
                <td>1..1</td>
                <td>Šia savybe pateikiamas valstybės valdymo ar savivaldos institucijos ar organizacijos, kuri yra informacinės sistemos valdytojas, pavadinimas.</td>
                <td>Ši savybė nurodo subjektą (organizaciją), atsakingą už katalogo prieinamumą.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_publisher">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Pavadinimas</td>
                <td>[dct:title](https://w3c.github.io/dxwg/dcat/#Property:resource_title)</td>
                <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
                <td>1..n</td>
                <td>IS tvarkomų duomenų katalogo pavadinimas turi nurodyti, kad tai konkrečios informacinės sistemos ar jos esminės dalies (posistemės) informacinė struktūra, kurios apimtyje yra tvarkomi duomenų rinkiniai.</td>
                <td>Šioje savybėje pateikiamas katalogui suteiktas pavadinimas.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_title">E</a></td>
            </tr>

            <tr class="data-table__header">
                <td>Kaupimo periodiškumas</td>
                <td>[dcat:accrualPeriodicity](http://purl.org/dc/terms/acrualPeriodicity)</td>
                <td>[dct:Frequency](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Frequency)</td>
                <td>0..1</td>
                <td>-</td>
                <td>Ši savybė nurodo registro katalogo dažnumą atnaujinama naujais / redaguotais duomenų rinkiniais.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_frequency">E</a></td>
            </tr>

            <tr class="data-table__header">
                <td>Duomenų rinkinys</td>
                <td>[dcat:dataset](http://www.w3.org/ns/dcat#dataset)</td>
                <td>[dcat:Dataset](http://www.w3.org/ns/dcat#Dataset)</td>
                <td>0..n</td>
                <td>Šia klase apibūdinama konkreti informacinė sistema – valstybės informacinės sistema ar registras, kurio apimtyje yra tvarkomi duomenų rinkiniai.</td>
                <td>Ši savybė susieja katalogą su duomenų rinkiniu, kuris yra katalogo įrašas.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_dataset">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Paslauga</td>
                <td>[dcat:service](http://www.w3.org/ns/dcat#service)</td>
                <td>[dcat:DataService](http://www.w3.org/ns/dcat#DataService)</td>
                <td>0..n</td>
                <td>-</td>
                <td>Ši savybė nurodo svetainę arba galinį tašką (angl. end-point) (duomenų paslaugą), įtrauktą į katalogą.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_service">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Tinklalapis</td>
                <td>[foaf:homepage](http://xmlns.com/foaf/0.1/homepage)</td>
                <td>[foaf:Document](http://xmlns.com/foaf/0.1/Document)</td>
                <td>0..1</td>
                <td>-</td>
                <td>Ši savybė nurodo tinklalapį, kuris yra pagrindinis katalogo puslapis.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_homepage">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Kalba</td>
                <td>[dct:language](https://w3c.github.io/dxwg/dcat/#Property:resource_language)</td>
                <td>[dct:LinguisticSystem](http://purl.org/dc/terms/LinguisticSystem)</td>
                <td>0..n</td>
                <td>-</td>
                <td>Ši savybė nurodo kalbą, naudojamą tekstiniuose metaduomenyse, apibūdinančiuose kataloge esančių duomenų rinkinių pavadinimus, aprašymus.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_language">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Licencija</td>
                <td>[dct:license](http://purl.org/dc/terms/license)</td>
                <td>[dct:LicenseDocument](http://purl.org/dc/terms/LicenseDocument)</td>
                <td>0..1</td>
                <td>-</td>
                <td>Ši savybė nurodo licenciją, pagal kurią galima naudoti arba pakartotinai naudoti katalogą.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_license">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Išleistas</td>
                <td>[dct:issued](http://purl.org/dc/terms/issued)</td>
                <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
                <td>0..1</td>
                <td>IS kontekste laikoma, kad katalogo paskelbimo data yra oficiali duomenų apie informacinės sistemos metaduomenis įsigaliojimo data.</td>
                <td>Šioje savybėje nurodoma oficiali katalogo paskelbimo data.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_release_date">E</a></td>
            </tr>

            <tr class="data-table__header">
                <td>Geografinė aprėptis</td>
                <td>[dct:spatial](http://purl.org/dc/terms/spatial)</td>
                <td>[dct:Location](http://purl.org/dc/terms/Location)</td>
                <td>0..1</td>
                <td>-</td>
                <td>Šioje savybėje nurodoma geografinė duomenų aprėptis.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_spatial">E</a></td>
            </tr>

            <tr class="data-table__header">
                <td>Temos taksonomija</td>
                <td>[dcat:themeTaxonomy](http://www.w3.org/ns/dcat#themeTaxonomy)</td>
                <td>[skos:ConceptScheme](http://www.w3.org/2004/02/skos/core#ConceptScheme)</td>
                <td>0..n</td>
                <td>-</td>
                <td>Ši savybė nurodo žinių organizavimo sistemą, naudojamą katalogo duomenų rinkiniams klasifikuoti.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_themes">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Pakeitimo data</td>
                <td>[dct:modified](https://w3c.github.io/dxwg/dcat/#Property:distribution_update_date)</td>
                <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
                <td>0..1</td>
                <td>-</td>
                <td>Šioje savybėje nurodoma naujausia katalogo pakeitimo data.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_update_date">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Turi sudedamąją dalį</td>
                <td>[dct:hasPart](https://w3c.github.io/dxwg/dcat/#Property:resource_has_part)</td>
                <td>[dcat:Catalog](http://www.w3.org/ns/dcat#Catalog)</td>
                <td>0..n</td>
                <td>IS kontekste, šiuo ryšiu gali būti įprasminamos valstybės informacinės sistemos ar registro reikšmingų veiklos sričių ar posistemių dalys.</td>
                <td>Ši savybė nurodo susijusį katalogą, kuris yra aprašyto katalogo dalis.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_has_part">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Yra sudedamoji dalis</td>
                <td>[dct:isPartPf](https://w3c.github.io/dxwg/dcat/#Property:dataset_in_series)</td>
                <td>[dcat:Catalog](http://www.w3.org/ns/dcat#Catalog)</td>
                <td>0..1</td>
                <td>-</td>
                <td>Ši savybė nurodo susijusį katalogą, į kurį fiziškai arba logiškai įtrauktas aprašomas katalogas.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_in_series">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Įrašas</td>
                <td>[dcat:record](http://www.w3.org/ns/dcat#record)</td>
                <td>[dcat:CatalogRecord](http://www.w3.org/ns/dcat#CatalogRecord)</td>
                <td>0..n</td>
                <td>-</td>
                <td>Ši savybė nurodo katalogo įrašą, kuris yra katalogo dalis.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_catalog_record">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Teisės</td>
                <td>[dct:rights](https://w3c.github.io/dxwg/dcat/#Property:resource_rights)</td>
                <td>[dct:RightsStatement](http://purl.org/dc/terms/RightsStatement)</td>
                <td>0..1</td>
                <td>-</td>
                <td>Ši savybė pateikia deklaraciją, kurioje nurodomos su katalogu susijusios teisės.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_rights">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Katalogas</td>
                <td>[dcat:catalog](http://www.w3.org/ns/dcat#catalog)</td>
                <td>[dcat:Catalog](http://www.w3.org/ns/dcat#Catalog)</td>
                <td>0..n</td>
                <td>-</td>
                <td>Ši savybė nurodo katalogą, kurio turinys domina šio katalogo kontekste.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_catalog">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Rengėjas</td>
                <td>[dct:creator](http://purl.org/dc/terms/creator)</td>
                <td>[foaf:Agent](http://xmlns.com/foaf/0.1/Agent)</td>
                <td>0..n</td>
                <td>IS Valdytojas</td>
                <td>Ši savybė nurodo subjektą, atsakingą už katalogo parengimą.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_creator">E</a></td>
            </tr>
            <tr class="data-table__header">
                <td>Teisinis pagrindas</td>
                <td>[dcatap:applicableLegislation](https://semiceu.github.io/uri.semic.eu-generated/r5r/release/3.0.0/#applicableLegislation)</td>
                <td>[eli:LegalResource](http://data.europa.eu/eli/ontology#LegalResource)</td>
                <td>0..n</td>
                <td>-</td>
                <td>Teisės aktas, kuris įpareigoja sukurti ir valdyti katalogą.</td>
		<td>P</td>
            </tr>
        </table>
   </dd>
</dl>


## Agentas

<dl>
    <dt>Apibrėžimas</dt>
    <dd>Bet kuris subjektas, atliekantis veiksmus, susijusius su pagrindinėmis (angl. Core) klasėmis: Katalogas, Duomenų rinkinys, Duomenų paslauga ir Distribucija.</dd>
    <dd>
 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Agentas</td>
                <td>Šioje savybėje pateikiamas agento pavadinimas. Ši savybė gali būti kartojama skirtingoms pavadinimo versijoms (pvz., pavadinimas skirtingomis kalbomis).</td>
                <td>-</td>
                <td>[foaf:Agent](http://xmlns.com/foaf/0.1/Agent)</td>
            </tr>
  </table>
 <table class="data-table simple">
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:5%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:5%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:35%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
            <tr class="data-table__header">
                <td>Pavadinimas</td>
                <td>[foaf:name](http://xmlns.com/foaf/0.1/name)</td>
                <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
                <td>1..n</td>
                <td>-</td>
                <td>Šioje savybėje pateikiamas agento pavadinimas. Ši savybė gali būti kartojama skirtingoms pavadinimo versijoms (pvz., pavadinimas skirtingomis kalbomis).</td>
		<td>P</td>
            </tr>
            <tr class="data-table__header">
                <td>Tipas</td>
                <td>[dct:type](http://purl.org/dc/terms/type)</td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
                <td>0..1</td>
                <td>-</td>
                <td>Ši savybė nurodo agento, kuris padaro prieinamu katalogą arba duomenų rinkinį, tipą.</td>
		<td>P</td>
            </tr>
            <tr class="data-table__header">
                <td>Identifikatorius</td>
                <td>[dct:identifier](http://purl.org/dc/terms/identifier)</td>
                <td>[adms:Identifier](https://w3c.github.io/dxwg/dcat/#Property:resource_identifier)</td>
                <td>0..1</td>
                <td>-</td>
                <td>Ši savybė nurodo agento, kuris padaro prieinamu katalogą arba duomenų rinkinį, identifikatorių.</td>
		<td>-</td>
            </tr>
        </table>
   </dd>
</dl>


## Tekstinis

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Tekstinis</td>
                <td>tekstinė vertė</td>
                <td> - </td>
                <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
            </tr>
           
        </table>

## Išteklius

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:30%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:30%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Išteklius</td>
                <td>Bet koks objektas, kurį galima aprašyti RDF</td>
                <td>Ši klasė apibrėžia abstrakčią sąvoką ir neturi savybių</td>
                <td>[rdfs:Resource](http://www.w3.org/2000/01/rdf-schema#Resource)</td>
            </tr>
           
        </table>


## Duomenų rinkinys

  <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:12%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:50%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Duomenų rinkinys</td>
                <td>Koncepcinė klasė, aprašanti kaupiamą / teikiamą informaciją. Sujungia katalogą su duomenų rinkiniu, kuris yra katalogo dalis.</td>
                <td>Šios klasės egzemplioriais apibūdinami  duomenų rinkiniai, tvarkomi informacinės sistemos apimtyje.
Kiekvienas duomenų rinkinys per katalogo įrašo sąryšį CatalogRecord, priskiriamas vienam informacinės sistemos (Catalog) atvejui.
Tokiu būdu aprašomi konkretūs duomenų rinkiniai, valdomi ir tvarkomi konkrečios informacinės sistemos apimtyje. 
Konkretaus duomenų rinkinio (Dataset) registravimo pagrindas informacinės sistemos (Catalog) apimtyje yra informacinės sistemos nuostatų patvirtinimas (IS gyvavimo ciklo metodikoje apibrėžta tvarka). 
Kiekvienas duomenų rinkinys įprasmina tam tikrą valstybės informacinės sistemos ar registro nuostatuose įvardintiną informacinės struktūros dalį. 
Duomenų rinkinys išskiriamas ir formuluojamas kaipinformacinės sistemosveiklos apimtyje suvokiama prasminga ir reikšminga koncepcija, apibūdinama reikšmingomis savybėmis/ atributais.
</td>
                <td>[dcat:Dataset](http://www.w3.org/ns/dcat#Dataset)</td>
            </tr>
           
        </table>


 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:5%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:5%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
            <tr>
        <td>Aprašymas</td>
        <td>[dct:description](http://purl.org/dc/terms/description)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..n</td>
        <td>Koncepcinio detalumo lygmens aprašymas, laikantisinformacinės sistemoslygmenyje arinformacinės sistemosvaldymo srityje nustatytos terminologijos ontologijos sąvokų ar duomenų rinkinių taikytinų informacinio modelio reikalavimų.</td>
        <td>Laisvu tekstu pateikiamas duomenų rinkinio aprašas. Galima pakartoti, jei aprašas yra keliomis kalbomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_description">E</a></td>
    </tr>
    <tr>
        <td>Pavadinimas</td>
        <td>[dct:title](http://purl.org/dc/terms/title)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Pateikiamas duomenų rinkiniui suteiktas pavadinimas. Galima pakartoti, jei pavadinimas pateikiamas keliomis kalbomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_title">E</a></td>
    </tr>
    <tr>
        <td>Identifikatorius</td>
        <td>[dct:identifier](https://w3c.github.io/dxwg/dcat/#Property:resource_identifier)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Pagrindinis duomenų rinkinio identifikatorius, pvz., URI, arba kitas unikalus identifikatorius katalogo kontekste.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_identifier">E</a></td>
    </tr>
    <tr>
        <td>Kitas identifikatorius</td>
        <td>[adms:identifier](http://www.w3.org/ns/adms#identifier)</td>
        <td>[adms:Identifier](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Identifier)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Antrinis duomenų rinkinio identifikatorius. Pavyzdžiai: MAST/ADS, DataCite, DOI, EZID, W3ID. Rekomendacija: įtraukti visus identifikatorius, kuriuos katalogas žino apie duomenų rinkinį.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#dereferenceable-identifiers">E</a></td>
    </tr>
    <tr>
        <td>Versija</td>
        <td>[dcat:version](http://www.w3.org/ns/dcat#version)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Duomenų rinkinio versijos identifikavimas (pavadinimas arba identifikatorius).</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_version">E</a></td>
    </tr>
   
    <tr>
        <td>Duomenų erdvė</td>
        <td>[dct:conformsTo](http://purl.org/dc/terms/conformsTo)</td>
        <td>[dct:Standard](http://purl.org/dc/terms/Standard)</td>
        <td>1..n</td>
        <td>Šaltinis: EUR-Lex - 52020DC0066 - EN - EUR-Lex (europa.eu)</td>
        <td>Nustatyta duomenų erdvė, kuriai atitinka aprašyta distribucija.</td>
        <td>P</td>
    </tr>
    <tr>
        <td>Kontaktinė informacija</td>
        <td>[dcat:contactPoint](http://www.w3.org/ns/dcat#contactPoint)</td>
        <td>[vcard:Kind](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Kind)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiama kontaktinė informacija, kurią galima naudoti siunčiant pastabas apie duomenų rinkinį.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_contact_point">E</a></td>
    </tr>
    <tr>
        <td>Duomenų rinkinio pateiktis</td>
        <td>[dcat:distribution](http://www.w3.org/ns/dcat#distribution)</td>
        <td>[dcat:Distribution](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė susieja duomenų rinkinį su platinimu.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_distribution">E</a></td>
    </tr>
    <tr>
        <td>Raktažodis</td>
        <td>[dcat:keyword](http://www.w3.org/ns/dcat#keyword)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiamas duomenų rinkinį apibūdinantis raktažodis arba žyma.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_keyword">E</a></td>
    </tr>
    <tr>
        <td>Duomenų skelbėjas</td>
        <td>[dct:publisher](https://w3c.github.io/dxwg/dcat/#Property:resource_publisher)</td>
        <td>[foaf:Agent](http://xmlns.com/foaf/0.1/Agent)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo subjektą (organizaciją), atsakingą už duomenų rinkinio prieinamumą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_publisher">E</a></td>
    </tr>
    <tr>
        <td>Geografinė vieta</td>
        <td>[dct:spatial](https://w3c.github.io/dxwg/dcat/#Property:dataset_spatial)</td>
        <td>[dct:Location](http://purl.org/dc/terms/Location)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo geografinę vietovę, kurią apima duomenų rinkinys.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_spatial_resolution">E</a></td>
    </tr>
    <tr>
        <td>Laikotarpis</td>
        <td>[dct:temporal](https://w3c.github.io/dxwg/dcat/#Property:dataset_temporal)</td>
        <td>[dct:PeriodOfTime](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Periodoftime)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo laikotarpį, kurį apima duomenų rinkinys.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_temporal">E</a></td>
    </tr>
    <tr>
        <td>Kategorija</td>
        <td>[dcat:theme](http://www.w3.org/ns/dcat#theme)</td>
        <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo duomenų rinkinio kategoriją. Duomenų rinkinys gali būti susietas su keliomis temomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_theme">E</a></td>
    </tr>
    <tr>
        <td>Prieigos teisės</td>
        <td>[dct:accessRights](http://purl.org/dc/terms/accessRights)</td>
        <td>[dct:RightsStatement](http://purl.org/dc/terms/RightsStatement)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė susijusi su informacija, kuri nurodo, ar duomenų rinkinys yra atviri duomenys, ar jam taikomi prieigos apribojimai, ar jis nėra viešas.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_access_rights">E</a></td>
    </tr>
    <tr>
        <td>Atitinka</td>
        <td>[dct:conformsTo](http://purl.org/dc/terms/conformsTo)</td>
        <td>[dct:Standard](http://purl.org/dc/terms/Standard)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo įgyvendinimo taisyklę arba kitą specifikaciją.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_conforms_to">E</a></td>
    </tr>
    <tr>
        <td>Rengėjas</td>
        <td>[dct:creator](http://purl.org/dc/terms/creator)</td>
        <td>[foaf:Agent](http://xmlns.com/foaf/0.1/Agent)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Subjektas, atsakingas už duomenų rinkinio parengimą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_creator">E</a></td>
    </tr>
    <tr>
        <td>Dokumentacija</td>
        <td>[foaf:page](http://xmlns.com/foaf/0.1/page)</td>
        <td>[foaf:Document](http://xmlns.com/foaf/0.1/Document)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo puslapį arba dokumentą apie šį duomenų rinkinį.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_landing_page">E</a></td>
    </tr>
    <tr>
        <td>Kaupimo periodiškumas</td>
        <td>[dct:accrualPeriodicity](https://w3c.github.io/dxwg/dcat/#Property:dataset_frequency)</td>
        <td>[dct:Frequency](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Frequency)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo, kaip dažnai atnaujinamas duomenų rinkinys.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_frequency">E</a></td>
    </tr>
    <tr>
        <td>Turi versiją</td>
        <td>[dcat:hasVersion](http://www.w3.org/ns/dcat#hasVersion)</td>
        <td>[dcat:Dataset](http://www.w3.org/ns/dcat#Dataset)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo susijusį duomenų rinkinį, kuris yra aprašyto duomenų rinkinio versija, leidimas arba adaptacija.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_has_version">E</a></td>
    </tr>
    <tr>
        <td>Yra referuota iš</td>
        <td>[dct:isReferencedBy](https://w3c.github.io/dxwg/dcat/#Property:resource_is_referenced_by)</td>
        <td>[rdfs:Resource](http://www.w3.org/2000/01/rdf-schema#Resource)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Susijęs šaltinis, pavyzdžiui, leidinys iš kurio pateikiamos nuorodos į duomenų rinkinį, kuriame jis cituojamas ir nukreipia į duomenų rinkinį.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_is_referenced_by">E</a></td>
    </tr>
    <tr>
        <td>Yra versija</td>
        <td>[dcat:isVersionOf](http://www.w3.org/ns/dcat#isVersionOf)</td>
        <td>[dcat:Dataset](http://www.w3.org/ns/dcat#Dataset)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Susijęs duomenų rinkinys, kurio aprašytasis duomenų rinkinys yra versija arba adaptacija.</td>
     <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_has_version">E</a></td>
    </tr>
    <tr>
        <td>Nukreipimo puslapis</td>
        <td>[dcat:landingPage](http://www.w3.org/ns/dcat#landingPage)</td>
        <td>[foaf:Document](http://xmlns.com/foaf/0.1/Document)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo tinklalapį, kuriame galima susipažinti su duomenų rinkiniu, jo distribucija ir (arba) papildoma informacija. Ji skirta nukreipti į pradinio duomenų teikėjo, o ne į trečiosios šalies, pavyzdžiui, agregatoriaus, svetainės puslapį.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_landing_page">E</a></td>
    </tr>
    <tr>
        <td>Kalba</td>
        <td>[dct:language](https://w3c.github.io/dxwg/dcat/#Property:resource_language)</td>
        <td>[dct:LinguisticSystem](http://purl.org/dc/terms/LinguisticSystem)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo duomenų rinkinio kalbą. Šią savybę galima pakartoti, jei duomenų rinkinys yra keliomis kalbomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_language">E</a></td>
    </tr>
    <tr>
        <td>Kilmė</td>
        <td>[dct:provenance](http://purl.org/dc/terms/provenance)</td>
        <td>[dct:ProvenanceStatement](http://purl.org/dc/terms/ProvenanceStatement)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiama deklaracija apie duomenų rinkinio kilmę.</td>
        <td>P</td>
    </tr>
    <tr>
        <td>Kvalifikuotas priskyrimas</td>
        <td>[prov:qualifiedAttribution](http://www.w3.org/ns/prov#qualifiedAttribution)</td>
        <td>[prov:Attribution](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Attribution)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė pateikia nuorodą į agentą, turintį tam tikrą atsakomybę už išteklių.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_qualified_attribution">E</a></td>
    </tr>
    <tr>
        <td>Kvalifikuotas ryšis</td>
        <td>[dcat:qualifiedRelation](http://www.w3.org/ns/dcat#qualifiedRelation)</td>
        <td>[dcat:Relationship](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Relationship)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė pateikia nuorodą į ryšio su kitu ištekliumi aprašymą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_qualified_relation">E</a></td>
    </tr>
    <tr>
        <td>Susijęs išteklius</td>
        <td>[dct:relation](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Relationship.relation)</td>
        <td>[rdfs:Resource](http://www.w3.org/2000/01/rdf-schema#Resource)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo susijusį išteklių.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_relation">E</a></td>
    </tr>
    <tr>
        <td>Išleidimo data</td>
        <td>[dct:issued](http://purl.org/dc/terms/issued)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Duomenų rinkinio oficialaus išleidimo (pvz., paskelbimo) data.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_release_date">E</a></td>
    </tr>
    <tr>
        <td>Pavyzdys</td>
        <td>[adms:sample](http://www.w3.org/ns/adms#sample)</td>
        <td>[dcat:Distribution](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo duomenų rinkinio pavyzdį.</td>
        <td>P</td>
    </tr>
    <tr>
        <td>Šaltinis</td>
        <td>[dct:source](http://purl.org/dc/terms/source)</td>
        <td>[dcat:Dataset](http://www.w3.org/ns/dcat#Dataset)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Susijęs duomenų rinkinys, iš kurio suformuotas aprašytas duomenų rinkinys.</td>
        <td>P</td>
    </tr>
    <tr>
        <td>Erdvinė raiška</td>
        <td>[dcat:spatialResolutionInMeters](http://www.w3.org/ns/dcat#spatialResolutionInMeters)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Mažiausias erdvinis atskyrimas, kurį galima atskirti duomenų rinkinyje, matuojamas metrais.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_spatial_resolution">E</a></td>
    </tr>
    <tr>
        <td>Laikotarpis</td>
        <td>[dcat:temporalResolution](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.temporalresolution)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Laikotarpis, kurį apima duomenų rinkinys.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_temporal_resolution">E</a></td>
    </tr>
    <tr>
        <td>Tipas</td>
        <td>[dct:type](http://purl.org/dc/terms/type)</td>
        <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo duomenų rinkinio tipą. Numatytas rekomenduojamas kontroliuojamo žodyno duomenų tipas.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_type">E</a></td>
    </tr>
    <tr>
        <td>Pakeitimo data</td>
        <td>[dct:modified](https://w3c.github.io/dxwg/dcat/#Property:distribution_update_date)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Naujausia duomenų rinkinio pakeitimo arba modifikavimo data.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_update_date">E</a></td>
    </tr>
    <tr>
        <td>Versijos pastabos</td>
        <td>[adms:versionNotes](http://www.w3.org/ns/adms#versionNotes)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šios versijos ir ankstesnės duomenų rinkinio versijos skirtumų aprašymas.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_version_notes">E</a></td>
    </tr>
    <tr>
        <td>Buvo sukurtas dėl</td>
        <td>[prov:wasGeneratedBy](http://www.w3.org/ns/prov#wasGeneratedBy)</td>
        <td>[prov:Activity](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Activity)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Veikla, dėl kurios buvo sukurtas duomenų rinkinys arba kuri suteikia verslo kontekstą duomenų rinkinio kūrimui.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_was_generated_by">E</a></td>
    </tr>
    <tr>
        <td>Yra dalis</td>
        <td>[dct:isPartOf](https://w3c.github.io/dxwg/dcat/#Property:dataset_in_series)</td>
        <td>[dcat:Catalog](http://www.w3.org/ns/dcat#Catalog)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo susijusį duomenų rinkinį, į kurį fiziškai arba logiškai įtrauktas aprašomas katalogas.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_in_series">E</a></td>
    </tr>
    <tr>
        <td>Teisinis pagrindas</td>
        <td>[dcatap:applicableLegislation](https://semiceu.github.io/uri.semic.eu-generated/r5r/release/3.0.0/#applicableLegislation)</td>
        <td>[eli:LegalResource](http://data.europa.eu/eli/ontology#LegalResource)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Teisės aktas, kurio pagrindu yra valdomas ir tvarkomas duomenų rinkinys.</td>
        <td>P</td>
    </tr>

	<!-- trūko 'follows' -->
	<tr>
        <td>Laikosi</td>
        <td>[cpsv:follows](http://purl.org/vocab/cpsv#follows)</td>
        <td>[cpsv:Rule](https://joinup.ec.europa.eu/solution/core-public-servicevocabulary)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši ypatybė susieja duomenų rinkinį su taisykle, kuri apibrėžia jo teisinį pagrindą.</td>
        <td>P</td>
    </tr>
	<!-- trūko 'hasPart' -->
	<tr>
		<td>Turi dalį</td>
		<td>[dct:hasPart](http://purl.org/dc/terms/hasPart)</td>
        <td>[dcat:Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset)</td>
        <td>0..n</td>
        <td>IS kontekste, šiuo ryšiu gali būti įprasminamos valstybės informacinės sistemos ar registro reikšmingų veiklos sričių ar posistemių dalys.</td>
        <td>Ši savybė nurodo susijusį duomenų rinkinį, kuris yra aprašyto duomenų rinkinio dalis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_has_part">E</a></td>
	</tr>
	<!-- trūko 'hasQualityAnnotation' -->
	<tr>
		<td>Turi kokybės anotaciją</td>
		<td>[dqv:hasQualityAnnotation](http://www.w3.org/ns/dqv#hasQualityAnnotation)</td>
        <td>[dqv:QualityAnnotation](https://www.w3.org/TR/vocab-dqv/#dqv:QualityAnnotation)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Nurodo, kiek nuoseklus yra duomenų rinkinys visoje sistemoje.</td>
        <td><a href="https://www.w3.org/TR/vocab-dqv/#dqv:hasQualityAnnotation">E</a></td>
	</tr>
	<!-- trūko 'hasQualityMeasurement' -->
	<tr>
		<td>Turi kokybės matavimą</td>
		<td>[dqv:hasQualityMeasurement](http://www.w3.org/ns/dqv#hasQualityMeasurement)</td>
        <td>[dqv:QualityMeasurement](https://www.w3.org/TR/vocab-dqv/#dqv:QualityMeasurement)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Nurodo, kaip patikimas yra pateiktas duomenų rinkinys.</td>
         <td><a href="https://www.w3.org/TR/vocab-dqv/#dqv:hasQualityMeasurement">E</a></td>
	</tr>
	<!-- trūko 'isReplacedBy' -->
	<tr>
		<td>Yra pakeistas</td>
		<td>[dct:isReplacedBy](http://purl.org/dc/terms/isReplacedBy)</td>
        <td>[dcat:Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši ypatybė nurodo susijusį duomenų rinkinį, kuris egiztuojantį duomenų rinkinį.</td>
         <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_replaces">E</a></td>
	</tr>
	<!-- trūko 'isRequiredBy' -->
	<tr>
		<td>Yra reikalaujamas</td>
		<td>[dct:isRequiredBy](http://purl.org/dc/terms/isRequiredBy)</td>
        <td>[dcat:Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši ypatybė nurodo susijusį duomenų rinkinį, kuriam reikalingas duomenų rinkinys.</td>
         <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_qualified_relation">E</a></td>
	</tr>
	<!-- trūko 'references' -->
	<tr>
		<td>Nurodo</td>
		<td>[dct:references](http://purl.org/dc/terms/references)</td>
        <td>[rdfs:Resource](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Resource)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši ypatybė pateikia tinklalapį su ryšio aprašu su kitu ištekliumi, kurį nurodo duomenų rinkinys. Ši ypatybė yra atvirkštinė dct:isReferencedBy. </td>
         <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_is_referenced_by">E</a></td>
	</tr>
	<!-- trūko 'replaces' -->
	<tr>
		<td>Pakeičia</td>
		<td>[dct:replaces](http://purl.org/dc/terms/replaces)</td>
        <td>[dcat:Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši ypatybė nurodo kitą duomenų rinkinį, kurį pakeičia duomenų rinkinys.</td>
         <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_replaces">E</a></td>
	</tr>
	<!-- trūko 'requires' -->
	<tr>
		<td>Reikalauja</td>
		<td>[dct:requires](http://purl.org/dc/terms/requires)</td>
        <td>[dcat:Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši ypatybė nurodo kitą duomenų rinkinį, kurio reikia duomenų rinkiniui.</td>
        <td>P</td>
	</tr>
	<!-- trūko 'versionInfo' -->
	<tr>
		<td>Versijos informacija</td>
		<td>[owl:versionInfo](http://www.w3.org/2002/07/owl#versionInfo)</td>
        <td>[rdfs:Literal](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Šioje ypatybėje yra versijos numeris arba kita informacija apie duomenų rinkinio versiją.</td>
         <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_version">E</a></td>
	</tr>
 </table>



## Duomenų paslauga

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Duomenų paslauga</td>
                <td>Operacijų rinkinys, suteikiantis prieigą prie vieno ar daugiau duomenų rinkinių arba duomenų apdorojimo funkcijų.</td>
                <td>-</td>
                <td>[dcat:DataService](http://www.w3.org/ns/dcat#DataService)</td>
            </tr>
           
        </table>

 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
<tr>
        <td>Identifikatorius</td>
        <td>[dct:identifier](http://purl.org/dc/terms/identifier)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Šioje savybėje nurodomas duomenų paslaugos identifikatorius.</td>
    </tr>
	<tr>
        <td>Prieigos taško aprašas</td>
        <td>[dcat:endpointDescription](http://www.w3.org/ns/dcat#endpointDescription)</td>
        <td>[rdfs:Resource](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Resource)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiamas paslaugų, prieinamų per galinius taškus, aprašymas, įskaitant jų operacijas, parametrus ir t. t. Pastaba. Šioje savybėje pateikiama konkreti informacija apie tikruosius galinių taškų egzempliorius, o dcterms:conformsTo naudojama bendram standartui ar specifikacijai, kurią galiniai taškai įgyvendina, nurodyti.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:data_service_endpoint_description">E</a></td>
    </tr>
<tr>
        <td>Raktažodis / žyma</td>
        <td>[dcat:keyword](http://www.w3.org/ns/dcat#keyword)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiamas duomenų paslaugą apibūdinantis raktažodis arba žyma.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_keyword">E</a></td>
    </tr>

<tr>
        <td>Aprašas</td>
        <td>[dct:description](http://purl.org/dc/terms/description)</td>
        <td>[rfds:Literal](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje laisvu tekstu pateikiamas duomenų paslaugos aprašas. Šią savybę galima pakartoti, jei aprašas pateikiamas keliomis kalbomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_description">E</a></td>
    </tr>

<tr>
        <td>Tema / kategorija</td>
        <td>[dcat:theme/category](http://www.w3.org/ns/dcat#theme)</td>
        <td>[skos:Concept](https://www.w3.org/2009/08/skos-reference/skos.html#Concept)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo duomenų paslaugos kategoriją. Duomenų paslauga gali būti susieta su keliomis temomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_theme">E</a></td>
    </tr>


<tr>
        <td>Duomenų teikėjas</td>
        <td>[dct:publisher](http://purl.org/dc/terms/publisher)</td>
        <td>[foaf:Agent](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Agent)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo subjektą (organizaciją), atsakingą už duomenų paslaugos prieinamumą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_publisher">E</a></td>
    </tr>

<tr>
        <td>Pateikia duomenų rinkinį</td>
        <td>[dct:servesDataset](http://www.w3.org/ns/dcat#servesdataset)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė referuoja į duomenų rinkinį, kurį duomenų paslauga platina. Pastaba: privaloma savybė, jei paslauga susijusi su didelės vertės duomenų rinkiniais.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:data_service_serves_dataset">E</a></td>
    </tr>

    <tr>
        <td>Pavadinimas</td>
        <td>[dct:title](http://purl.org/dc/terms/title)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiamas duomenų paslaugai suteiktas pavadinimas. Galima pakartoti, jei pavadinimas pateikiamas keliomis kalbomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_title">E</a></td>
    </tr>
  <!-- trūko 'licence' -->
	<tr>
        <td>Licencija</td>
        <td>[dct:licence](http://purl.org/dc/terms/license)</td>
        <td>[dct:LicenseDocument](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#LicenceDocument)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo licenciją, pagal kurią platinama duomenų paslauga. Pastaba: privaloma savybė, jei paslauga susijusi su didelės vertės duomenų rinkiniais.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_license">E</a></td>
    </tr>
	<!-- trūko 'access rights' -->
	<tr>
        <td>Prieigos teisės</td>
        <td>[dct:accessRights](http://purl.org/dc/terms/accessRights)</td>
        <td>[dct:RightsStatement](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Rightsstatement)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė susijusi su informacija, kuri nurodo, ar duomenų paslauga yra atvira, ar jai taikomi prieigos apribojimai, ar ji nėra vieša.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_access_rights">E</a></td>
    </tr>
	<!-- trūko 'conforms to' -->
	<tr>
        <td>Atitinka</td>
        <td>[dct:conformsTo](http://purl.org/dc/terms/conformsTo)</td>
        <td>[dct:Standard](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Standard)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo įgyvendinimo taisyklę arba kitą specifikaciją.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:record_conforms_to">E</a></td>
    </tr>
	<!-- trūko 'follows' -->
	<tr>
        <td>Laikosi</td>
        <td>[cpsv:follows](http://purl.org/vocab/cpsv#follows)</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>P</td>
    </tr>
	<!-- trūko 'landingPage' -->
	<tr>
        <td>Nukreipimo puslapis</td>
        <td>[dcat:landingPage](http://www.w3.org/ns/dcat#landingPage)</td>
        <td>[foaf:Document](http://xmlns.com/foaf/0.1/Document)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo tinklalapį, kuriame galima susipažinti su duomenų paslauga, jos distribucija ir (arba) papildoma informacija. Ji skirta nukreipti į pradinio duomenų paslaugos teikėjo, o ne į trečiosios šalies, pavyzdžiui, agregatoriaus, svetainės puslapį.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_landing_page">E</a></td>
    </tr>

<tr>
        <td>Tipas</td>
        <td>[dct:type](http://purl.org/dc/terms/type)</td>
        <td>[skos:Concept](https://www.w3.org/2009/08/skos-reference/skos.html#Concept)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo duomenų paslaugos tipą. Numatytas rekomenduojamas kontroliuojamo žodyno duomenų paslaugos tipas.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_type">E</a></td>
    </tr>

    <tr>
        <td>Paslaugos kokybė</td>
        <td>[foaf:page](http://xmlns.com/foaf/0.1/page)</td>
        <td>[foaf:Document](http://xmlns.com/foaf/0.1/Document)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Ši savybė leidžia nurodyti tinklalapį, kuriame pateikiama išsami informacija apie teikiamos paslaugos kokybę bei kita aktuali informacija. Privaloma savybė, jei paslauga susijusi su didelės vertės duomenų rinkiniais.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_landing_page">E</a></td>
    </tr>
    <tr>
        <td>Kontaktinė informacija</td>
        <td>[dcat:contactPoint](http://www.w3.org/ns/dcat#contactPoint)</td>
        <td>[vcard:Kind](http://www.w3.org/2006/vcard/ns#Kind)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiama kontaktinė informacija, kurią galima naudoti siunčiant pastabas apie duomenų paslaugą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_contact_point">E</a></td>
    </tr>
    <tr>
        <td>Tinklalapis</td>
        <td>[dcat:endpointURL](http://www.w3.org/ns/dcat#endpointURL)></td>
        <td>[rdfs:Resource](http://www.w3.org/2000/01/rdf-schema#Resource)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Šioje savybėje galinio punkto URL turi būti nuolatinis. Tai reiškia, kad leidėjai turėtų daryti viską, kad išlaikytų stabilią ir esamą vertę.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:data_service_endpoint_url">E</a></td>
    </tr>

## Kategorija, Teikėjo tipas, Statusas

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:12%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:50%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Kategorija, Teikėjo tipas, Statusas</td>
                <td></td>
                <td></td>
                <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
            </tr>
           
        </table>


## Pateiktis

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:20%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:40%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Pateiktis</td>
                <td>Fizinė duomenų rinkinio išraiškos forma tam tikru formatu arba duomenų rinkinio realizacija.</td>
                <td>Ši klasė apibūdina konkretų ir aktyviai veikiantį duomenų rinkinio įgyvendinimą informacinėje sistemoje - valstybinės informacinės sistemos arba duomenų valdymo aplinkoje, tokioje kaip duomenų bazės lentelė, duomenų failai, saugomi duomenų saugykloje, struktūrizuoti ir pusiau struktūrizuoti failai uždarame intranete arba interneto erdvėje. 

IS kontekste, šios klasės prioritetinis ir didžiausios apimties taikymas yra informacinės sistemos aplinkoje tvarkomų duomenų rinkinių realizacijų aprašymui, ir toliau jų modelių detalizavimui klasėmis DataObjectTypeSpecification ir DataElement.
</td>
                <td>[dcat:Distribution](http://www.w3.org/ns/dcat#Distribution)</td>
            </tr>
           
        </table>

 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
            <tr>
        <td>Prieigos URL</td>
        <td>[dcat:accessURL](http://www.w3.org/ns/dcat#accessURL)</td>
        <td>[rdfs:Resource](http://www.w3.org/2000/01/rdf-schema#Resource)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiamas URL, kuris suteikia prieigą prie duomenų rinkinio platinimo.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_access_url">E</a></td>
    </tr>
    <tr>
        <td>Licencija</td>
        <td>[dct:license](http://purl.org/dc/terms/license)</td>
        <td>[dct:LicenseDocument](http://purl.org/dc/terms/LicenseDocument)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Ši savybė nurodo licenciją, pagal kurią platinama distribucija.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_license">E</a></td>
    </tr>
	<tr>
        <td>Prieinamumas</td>
        <td>[dcatap:availability](http://data.europa.eu/r5r/availability)</td>
        <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Nurodoma, kiek laiko planuojama išlaikyti duomenų rinkinio platinimą.</td>
        <td>P</td>
    </tr>
	<!-- trūko 'Description' -->
	<tr>
        <td>Aprašas</td>
        <td>[dct:description](http://purl.org/dc/terms/description)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje laisvu tekstu pateikiamas pateikties aprašas. Šią savybę galima pakartoti, jei aprašoma keliomis (lygiagrečiomis) kalbomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_description">E</a></td>
    </tr>
	<!-- trūko 'format' -->
	<tr>
        <td>Formatas</td>
        <td>[dct:format](http://purl.org/dc/terms/format)</td>
        <td>[dct:MediaTypeOrExtent](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#MediaTypeorExtent)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Pateikties failų formatas.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_format">E</a></td>
    </tr>
	<!-- trūko 'access service' -->
	<tr>
        <td>Prieigos paslauga</td>
        <td>[dcat:accessService](http://www.w3.org/ns/dcat#accessService)</td>
        <td>[dcat:DataService](http://www.w3.org/ns/dcat#DataService)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo duomenų paslaugą per kurią prieinama duomenų pateiktis</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_access_service">E</a></td>
    </tr>
	<!-- trūko 'byte size' -->
	<tr>
        <td>Dydis baitais</td>
        <td>[dcat:byteSize](http://www.w3.org/ns/dcat#byteSize)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo pateikties dydį baitais. Tai turi būti įvesta kaip xsd:decimal.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_size">E</a></td>
    </tr>
	<!-- trūko 'downloadURL' -->
	<tr>
        <td>parsisiuntimo URL</td>
        <td>[dcat:downloadURL](http://www.w3.org/ns/dcat#downloa)</td>
        <td>[rdfs:Resource](http://www.w3.org/2000/01/rdf-schema#Resource)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje nuosavybėje yra URL, kuris yra tiesioginė nuoroda į atsisiunčiamą failą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_download_url">E</a></td>
    </tr>
	<tr>
    <td>medijos tipas</td>
		<td>[dcat:mediaType](http://purl.org/dc/terms/mediaType)</td>
		<td>[dct:MediaType](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Mediatype)</td>
		<td>0..1</td>
		<td>-</td>
		<td>Ši savybė nurodo platinimo laikmenos tipą, kaip apibrėžta IANA valdomas žodynas</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_media_type">E</a></td>
	</tr>
	
	<tr>
		<td>kontrolinė suma</td>
		<td>[spdx:checksum](http://spdx.org/rdf/terms#checksum)</td>
		<td>[spdx:Checksum](http://spdx.org/rdf/terms#Checksum)</td>
		<td>0..1</td>
		<td>-</td>
		<td>Ši savybė suteikia mechanizmą, leidžiantį patikrinti pateikties turinio vientisumą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_checksum">E</a></td>
	</tr>
	<tr>
		<td>suspaudimo formatas</td>
		<td>[dcat:compressFormat](http://www.w3.org/ns/dcat#compressFormat)</td>
		<td>[dct:MediaType](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Mediatype)</td>
		<td>0..1</td>
		<td>-</td>
		<td>Ši savybė nurodo failo, kuriame yra duomenys, formatą esantys suspaustoje formoje, pvz. sumažinti dydį atsisiunčiamo failo.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_compression_format">E</a></td>
	</tr>
	<tr>
		<td>turi politiką</td>
		<td>[odrl:hasPolicy](http://www.w3.org/ns/odrl/2/hasPolicy)</td>
		<td>[odrl:Policy](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Policy)</td>
		<td>0..1</td>
		<td>-</td>
		<td>Ši nuosavybė reiškia politiką, išreiškiančią su pateiktimi susijusias teises, jei naudojamas ODRL žodynas.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_has_policy">E</a></td>
	</tr>
	<tr>
		<td>išleista</td>
		<td>[dct:issued](http://purl.org/dc/terms/issued)</td>
		<td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
		<td>0..1</td>
		<td>-</td>
		<td>Ši savybė nurodo datą, kai pateiktis buvo pirmą kartą išleista.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_release_date">E</a></td>
	</tr>
	<tr>
		<td>atnaujinimo / pakeitimo data</td>
		<td>[dct:modified](http://purl.org/dc/terms/modified)</td>
		<td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
		<td>0..1</td>
		<td>-</td>
		<td>Šioje savybėja nurodoma pateikties naujausio pakeitimo / atnaujinimo data</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_update_date">E</a></td>
	</tr>
	<tr>
		<td>kalba</td>
		<td>[dct:language](http://purl.org/dc/terms/language)</td>
		<td>[dct:LinguisticSystem](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Linguisticsystem)</td>
		<td>0..1</td>
		<td>Ši savybė turėtų būti kartojama, jei yra įvairių pateikties versijų skirtingomis kalbomis</td>
		<td>Ši savybė nurodo pateikties duomenų kalbą. </td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_language">E</a></td>
	</tr>
	<tr>
		<td>susijusi schema</td>
		<td>[dct:conformsTo](http://purl.org/dc/terms/conformsTo)</td>
		<td>[dct:Standard](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Standard)</td>
		<td>0..n</td>
		<td>-</td>
		<td>Ši savybė nurodo nustatytą schemą, kurią atitinka aprašoma pateiktis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_conforms_to">E</a></td>
	</tr>
	<tr>
		<td>(failų) pakavimo formatas</td>
		<td>[dcat:packageFormat](http://www.w3.org/ns/dcat#packageFormat)</td>
		<td>[dct:MediaType](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Mediatype)</td>
		<td>0..1</td>
		<td>-</td>
		<td>Ši savybė nurodo failo, kuriame yra vienas ar daugiau duomenų, formatą
failai sugrupuoti, pvz. kad būtų įjungtas susijusių failų rinkinys
atsisiųsta kartu. Jis TURĖTŲ būti išreikštas naudojant laikmenos tipą kaip
apibrėžtas oficialiame IANA tvarkomame žiniasklaidos tipų registre.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_packaging_format">E</a></td>
	</tr>
	<tr>
		<td>puslapis (dokumentacija)</td>
		<td>[foaf:page](http://xmlns.com/foaf/0.1/page)</td>
		<td>[foaf:Document](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Document)</td>
		<td>-0..n</td>
		<td>-</td>
		<td>Ši savybė nurodo į dokumentą su informacija apie platinimą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_homepage">E</a></td>
	</tr>
	<tr>
		<td>teisės</td>
		<td>[dct:rights](http://purl.org/dc/terms/rights)</td>
		<td>[dct:RightsStatement](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Rightsstatement)</td>
		<td>0..1</td>
		<td>-</td>
		<td>Ši savybė nurodo informacinį pareiškimą, kuriame nurodytos prieigos
ir pateikties valdymo teisės.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_rights">E</a></td>
	</tr>
	<tr>
		<td>erdvinė skiriamoji geba (metrais)</td>
		<td>[dcat:spatialResolutionInMeters](http://www.w3.org/ns/dcat#spatialResolutionInMeters)</td>
		<td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
		<td>0..n</td>
		<td>-</td>
		<td>Ši savybė nurodo minimalią erdvinę skiriamąją gebą, matuojamą metrais.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_spatial_resolution">E</a></td>
	</tr>
	<tr>
		<td>statusas</td>
		<td>[adms:status](http://www.w3.org/ns/adms#status)</td>
		<td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
		<td>0..1</td>
		<td>-</td>
		<td>Nurodomas pateikties brandos lygmuo</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_status">E</a></td>
	</tr>
	<tr>
		<td>pavadinimas</td>
		<td>[dct:title](http://purl.org/dc/terms/title)</td>
		<td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
		<td>0..n</td>
		<td>-</td>
		<td>Šioje nuosavybėje yra aprašomasis pateikties pavadinimas. 
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_title">E</a></td>
</td>
	</tr>
	<tr>
		<td>laiko skiriamoji geba</td>
		<td>[dcat:temporalResolution](http://www.w3.org/ns/dcat#temporalResolution)</td>
		<td>[xsd:duration](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
		<td>0..n</td>
		<td>-</td>
		<td>Ši savybė nurodo minimalią laiko skiriamąją gebą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_temporal_resolution">E</a></td>
	</tr>	
	<tr>
        <td>Licencija</td>
        <td>[dct:license](http://purl.org/dc/terms/license)</td>
        <td>[dct:LicenseDocument](http://purl.org/dc/terms/LicenseDocument)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Ši savybė nurodo licenciją, pagal kurią platinama distribucija.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_license">E</a></td>
    </tr>
   </table>

## Licencijos dokumentas

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Licencijos dokumentas</td>
                <td>Teisinis dokumentas, kuriuo suteikiamas oficialus leidimas ką nors daryti su ištekliais.</td>
                <td> - </td>
                <td>[dct:LicenseDocument](http://purl.org/dc/terms/LicenseDocument)</td>
            </tr>
           
        </table>

 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
              <tr>
        <td>Tipas</td>
        <td>[dct:type](http://purl.org/dc/terms/type)</td>
        <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo licencijos dokumento tipą. Numatytas rekomenduojamas kontroliuojamo žodyno duomenų tipas.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_type">E</a></td>
    </tr>
</table>


## Kategorijų schema

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:12%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:50%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Kategorijų schema</td>
                <td></td>
                <td></td>
                <td>[skos:ConceptScheme](http://www.w3.org/2004/02/skos/core#ConceptScheme)</td>
            </tr>
           
        </table>

 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
            <tr>
        <td>Pavadinimas</td>
        <td>[dct:title](http://purl.org/dc/terms/title)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Kategorijos schemos pavadinimas.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_title">E</a></td>
    </tr>
</table>


## Teisinis šaltinis

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Teisinis šaltinis</td>
                <td>Teisiniai šaltiniai - tai teisės aktai, politika ar politikos kryptys, kurie yra taisyklės, kuriomis apibrėžiamas bazinių registrų ir kitų informacinių sistemų paslaugos. 
Pastaba: Teisinių išteklių aprašymai ateityje numatomi būti pateikti pagal ELI ontologiją.
</td>
                <td> - </td>
                <td>[eli:LegalResource](http://data.europa.eu/eli/ontology#LegalResource)</td>
            </tr>
           
        </table>

 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
             <tr>
        <td>Tipas</td>
        <td>[dct:type](http://purl.org/dc/terms/type)</td>
        <td>[eli:ResourceType](http://data.europa.eu/eli/ontology#ResourceType)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Ši savybė nurodo teisinio ištekliaus tipą (pvz., "Direktyva", „Règlement grand ducal“, „įstatymas“, „Règlement ministériel“, „projektas pasiūlymas“, „Parlamento aktas“ ir t. t.). Valstybės narės raginamos sudaryti savo teisės aktų sąrašą atitinkamoje sąvokų schemoje.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_type">E</a></td>  
</tr>
    <tr>
        <td>Aprašas</td>
        <td>[dct:description](http://purl.org/dc/terms/description)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiama aprašomoji tekstinė informacija apie teisinį išteklių. Šią savybę reikėtų pakartoti, jei yra įvairių teksto versijų skirtingomis kalbomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_description">E</a></td>
    </tr>
    <tr>
        <td>Identifikatorius</td>
        <td>[dcterms:identifier](http://purl.org/dc/terms/identifier)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiamas taisyklės identifikatorius.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_identifier">E</a></td>
    </tr>
    <tr>
        <td>Nuoroda</td>
        <td>[rdfs:seeAlso](http://www.w3.org/2000/01/rdf-schema#seeAlso)</td>
        <td>[rdfs:Resource](http://www.w3.org/2000/01/rdf-schema#Resource)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė aprašo išteklių, susijusį su konkrečiu aprašomu teisiniu ištekliu.</td>
        <td>P</td>
    </tr>
    <tr>
        <td>Susijęs</td>
        <td>[dcterms:relation](http://purl.org/dc/terms/relation)</td>
        <td>[eli:LegalResource](http://data.europa.eu/eli/ontology#LegalResource)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė reiškia kitą teisinių išteklių klasės egzempliorių, susijusį su konkrečiu aprašomu teisiniu ištekliu.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_relation">E</a></td>
    </tr>
</table>

## Taisyklė

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Taisyklė (Rule)</td>
                <td>Taisyklė - tai dokumentas, kuriame nustatomos konkrečios gairės ar procedūros, kurių laikosi bazinis registras. Jame gali būti pateikiama informacija ir keliami reikalavimai viešojo bazinio registro teikiamoms paslaugoms.</td>
                <td> - </td>
                <td>[cpsv:Rule](http://purl.org/vocab/cpsv#Rule)</td>
            </tr>
           
        </table>
<br>
       <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
             <tr>
        <td>Aprašymas</td>
        <td>[dct:description](http://purl.org/dc/terms/description)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Šioje savybėje pateikiama aprašomoji tekstinė informacija apie taisyklę. Ši savybė turėtų būti kartojama, jei yra įvairių teksto versijų skirtingomis kalbomis.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_description">E</a></td>
    </tr>
    <tr>
        <td>Identifikatorius</td>
        <td>[dct:identifier](http://purl.org/dc/terms/identifier)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Šioje savybėje nurodomas taisyklės identifikatorius.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_identifier">E</a></td>
    </tr>
    <tr>
        <td>Pavadinimas</td>
        <td>[dct:title](http://purl.org/dc/terms/title)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Ši savybė nurodo aprašomąjį ištekliaus pavadinimą arba vardą. Šis savybė turėtų būti kartojama, jei yra įvairių teksto versijų skirtingomis kalbomis.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_title">E</a></td>
    </tr>
      <tr>
        <td>Įgyvendina</td>
        <td>[cpsv:implements](http://purl.org/vocab/cpsv#implements)</td>
        <td>[eli:LegalResource](http://data.europa.eu/eli/ontology#LegalResource)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė susieja taisyklę su atitinkamais teisės aktais ar politikos dokumentais, pvz. teisinį šaltinį, kuriame apibrėžtos taisyklės.</td>
        <td>P</td>
    </tr>
    <tr>
        <td>Kalba</td>
        <td>[dct:language](http://purl.org/dc/terms/language)</td>
        <td>[dct:LinguisticSystem](http://purl.org/dc/terms/LinguisticSystem)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo kalbą (-as), kuria (-iomis) galima naudotis taisykle. Ji gali būti viena ar kelios kalbos, pvz., šalyse, kuriose yra daugiau kalbų, nei viena oficiali kalba.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_language">E</a></td>
    </tr>
    <tr>
        <td>Tipas</td>
        <td>[dct:type](http://purl.org/dc/terms/type)</td>
        <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo taisyklės tipą. Joje turi būti naudojamas kontroliuojama žodynas.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_type">E</a></td>
    </tr>

  </table>


## Viešoji institucija

          <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Viešoji insitucija (PublicOrganisation)</td>
                <td>Viešoji institucija yra Agentas, kuris atsakingas už viešųjų paslaugų teikimą. Čia naudojama klasė iš Pagrindinio institucijų žodyno, taip pat pagrįsto W3C Organizacijų ontologija.</td>
                <td> - </td>
                <td>[cv:PublicOrganisation](http://data.europa.eu/m8g/PublicOrganisation)</td>
            </tr>
           
        </table>
         <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
             <tr>
        <td>Identifikatorius</td>
        <td>[dct:identifier](http://purl.org/dc/terms/identifier)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Ši savybė nurodo Agento identifikatorių.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_identifier">E</a></td>
    </tr>
    <tr>
        <td>Pavadinimas</td>
        <td>[dct:title](http://purl.org/dc/terms/title)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Ši savybė nurodo institucijos pavadinimą.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_title">E</a></td>
    </tr>
    <tr>
        <td>Pageidaujama antraštė</td>
        <td>[skos:prefLabel](http://www.w3.org/2004/02/skos/core#prefLabel)<br>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Ši savybė naudojama organizacijai pavadinti, jei naudojamas pageidaujamas pavadinimą. Šią savybę reikėtų pakartoti, jei pateikiama keliomis kalbomis.</td>
        <td>P</td>
    </tr>
    <tr>
        <td>Geografinė vietovė</td>
        <td>[dct:spatial](http://purl.org/dc/terms/spatial)</td>
        <td>[dct:Location](http://purl.org/dc/terms/Location)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Ši savybė nurodo geografinį arba administracinį regioną, kurį apima institucija. Šios savybės reikšmė turėtų būti URI iš Administracinio teritorinių vienetų pavadintų institucijų sąrašo, kurį tvarko Leidinių biuro Metaduomenų registras.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_spatial_resolution">E</a></td>
    </tr>
    <tr>
        <td>Adresas</td>
        <td>[locn:address](http://www.w3.org/ns/locn#address)</td>
        <td>[locn:Address](http://www.w3.org/ns/locn#Address)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo adresą, kaip konceptualiai apibrėžta INSPIRE adreso atvaizdavimo duomenų tipu.</td>
        <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_spatial">E</a></td>
    </tr>
    <tr>
        <td>Klasifikacija</td>
        <td>[org:classification](http://www.w3.org/ns/org#classification)<br>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė Nurodo institucijos klasifikaciją pagal tam tikrą klasifikavimo schemą.</td>
        <td>P</td>
    </tr>
    <tr>
        <td>Pagrindinis puslapis</td>
        <td>[foaf:homepage](http://xmlns.com/foaf/0.1/homepage)</td>
        <td>[foaf:Document](http://xmlns.com/foaf/0.1/Document)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė kreipia į institucijos pagrindinę interneto svetainę.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_homepage">E</a></td>
    </tr>

          </table>


## Informacinės sistemos paslauga

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Informacinės sistemos paslauga</td>
                <td>Ši klasė atvaizduoja gebėjimą atlikti viešosios paslaugos tiekimo procesus ir egzistuoja nepriklausomai nuo to, ar ja naudojamasi, ar ne. Tai veiksmų, kuriuos atlieka viešojo administravimo institucija arba kurie atliekami jos vardu piliečio, verslo ar kitos viešosios įstaigos naudai, rinkinys.</td>
                <td> - </td>
                <td>[cpsv:PublicService](http://purl.org/vocab/cpsv#PublicService)</td>
            </tr>
           
        </table>
 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:60%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
   <tr>
        <td>Aprašymas</td>
        <td>[dct:description](http://purl.org/dc/terms/description)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Ši savybė naudojama paslaugai aprašyti naudojant laisvu tekstu. Gali būti kartojama, jei aprašas keliomis kalbomis.</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_description">E</a></td>
</tr>
    <tr>
        <td>Identifikatorius</td>
        <td>[dcterms:identifier](http://purl.org/dc/terms/identifier)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Šioje savybėje pateikiamas oficialus registro paslaugos identifikavimas.</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_identifier">E</a></td>
    </tr>
    <tr>
        <td>Pavadinimas</td>
        <td>[dct:title](http://purl.org/dc/terms/title)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..n</td>
        <td>-</td>
        <td>Ši savybė reiškia oficialų registro paslaugos pavadinimą. Gali būti kartojama, jei pavadinimas keliomis kalbomis.</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_title">E</a></td>
    </tr>
    <tr>
        <td>Turi dalį</td>
        <td>[dcterms:hasPart](http://purl.org/dc/terms/hassPart)</td>
        <td>[cpsv:PublicService](http://purl.org/vocab/cpsv#PublicService)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo susijusią registro paslaugą, kuri yra įtraukta arba fiziškai, arba logiškai įeina į aprašomą išteklių. Naudojama bazinių registrų registrams aprašyti.</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_has_part">E</a></td>
    </tr>
   <tr>
        <td>Yra sudedamoji dalis</td>
        <td>[dcterms:isPartOf](http://purl.org/dc/terms/isPartOf)</td>
        <td>[cpsv:PublicService](http://purl.org/vocab/cpsv#PublicService)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo susijusią registro paslaugą, į kurią yra įtraukta arba fiziškai, arba logiškai įeina aprašomas išteklius. Naudojama bazinių registrų registrams aprašyti.</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_in_series">E</a></td>
    </tr>
    <tr>
        <td>Pagrindinis puslapis</td>
        <td>[foaf:homepage](http://xmlns.com/foaf/0.1/homepage)</td>
        <td>[foaf:Document](http://xmlns.com/foaf/0.1/Document)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo registro paslaugos pagrindinį puslapį.</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:catalog_homepage">E</a></td>
    </tr>
    <tr>
        <td>Rezultatas (duomenų išteklius)</td>
        <td>[cpsv:produces](http://purl.org/vocab/cpsv#produces)</td>
        <td>[cv:Output](http://data.europa.eu/m8g/Output)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė apibrėžia paslaugos išvestį kaip prieinamą duomenų išteklių ir valdomą bazinio registro paslaugos. Išvestis taip pat turi būti aprašyta kaip cat:Catalog, dcat:Dataset arba dcat:DataService.</td>
                   <td>P</td>
    </tr>
    <tr>
        <td>Geografinė vietovė</td>
        <td>[dct:spatial](http://purl.org/dc/terms/spatial)</td>
        <td>[dct:Location](http://purl.org/dc/terms/Location)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje nurodomas geografinis arba administracinis regionas, kurį apima registro paslauga.</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_spatial">E</a></td>
    </tr>
    <tr>
        <td>Statusas</td>
        <td>[adms:status](http://www.w3.org/ns/adms#status)td>
        <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo registro paslaugos būseną (t. y. aktyvi, neaktyvi, kuriama ir t. t.) pagal iš anksto nustatytą žodyną.</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_status">E</a></td>
    </tr>
    <tr>
        <td>Tematinė sritis</td>
        <td>cv:thematicArea</td>
        <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo pagrindinę (-es) registro temą (-as) pagal apibrėžtą klasifikavimo schemą.</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_theme">E</a></td>
    </tr>
    <tr>
        <td>Tipas</td>
        <td>[dct:type](http://purl.org/dc/terms/type)</td>
        <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Ši savybė nurodo registro paslaugos tipą, aprašytą sąvokų rinkinyje (pvz., bazinis registras ir bazinių registrų registras).</td>
                   <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:resource_type">E</a></td>
    </tr>
  </table>

## Katalogo įrašas

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Katalogo įrašas</td>
                <td>Duomenų rinkinio įrašo kataloge aprašas.</td>
                <td> - </td>
                <td>[dcat:CatalogRecord](http://www.w3.org/ns/dcat#CatalogRecord)</td>
            </tr>
           
        </table>
<br>
 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:60%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
             <tr>
        <td>Pagrindinė tema</td>
        <td>[foaf:primaryTopic](http://xmlns.com/foaf/0.1/primaryTopic)</td>
        <td>[dcat:Dataset](http://www.w3.org/ns/dcat#Dataset)<br>[dcat:Dataservice](http://www.w3.org/ns/dcat#DataService)<br>[dcat:Catalog](http://www.w3.org/ns/dcat#Catalog)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Nuoroda į įraše aprašytą duomenų rinkinį, duomenų paslaugą arba katalogą. Katalogo įrašas bus nuoroda į vieną katalogo vienetą. Tai gali būti duomenų rinkinys arba duomenų paslauga.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:record_primary_topic">E</a></td>
    </tr>
    <tr>
        <td>Pakeitimo data</td>
        <td>[dct:modified](http://purl.org/dc/terms/modified)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Šioje savybėje nurodoma naujausia katalogo įrašo pakeitimo arba modifikavimo data.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:record_update_date">E</a></td>
    </tr>
    <tr>
        <td>Taikymo profilis</td>
        <td>[dcterms:conformsTo](http://purl.org/dc/terms/conformsTo)</td>
        <td>[dct:Standard](http://purl.org/dc/terms/Standard)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Taikymo profilis, kurį atitinka duomenų rinkinio metaduomenys.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:record_conforms_to">E</a></td>
    </tr>
    <tr>
        <td>Pokyčio tipas</td>
        <td>[adms:status](http://www.w3.org/ns/adms#status)</td>
        <td>[skos:Concept](http://www.w3.org/2004/02/skos/core#Concept)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Katalogo įrašo statusas duomenų rinkinio redakcinio srauto ir duomenų paslaugų aprašymų kontekste.</td>
                <td>P</td>
    </tr>
    <tr>
        <td>Įtraukimo į sąrašą data</td>
        <td>[dct:issued](http://purl.org/dc/terms/issued)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Duomenų rinkinio aprašymo įtraukimo į katalogą data.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:record_listing_date">E</a></td>
    </tr>
    <tr>
        <td>Aprašymas</td>
        <td>[dct:description](http://purl.org/dc/terms/description)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Šioje savybėje laisvu tekstu pateikiamas aprašas. Galima pakartoti, jei aprašoma keliomis kalbomis.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:record_description">E</a></td>
    </tr>
    <tr>
        <td>Kalba</td>
        <td>[dct:language](http://purl.org/dc/terms/language)</td>
        <td>[dct:LinguisticSystem](http://purl.org/dc/terms/LinguisticSystem)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Kalba, vartojama tekstiniuose metaduomenyse, apibūdinančiuose duomenų rinkinio pavadinimus, aprašymus ir t. t. Galima pakartoti, jei metaduomenys pateikiami keliomis kalbomis.</td>
                <td>P</td>
    </tr>
    <tr>
        <td>Pirminiai metaduomenys</td>
        <td>[dct:source](http://purl.org/dc/terms/source)</td>
        <td>[dcat:CatalogRecord](http://www.w3.org/ns/dcat#CatalogRecord)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Pirminiai (šaltinio) metaduomenys, kurie buvo naudojami kuriant duomenų rinkinio metaduomenis.</td>
        <td>P</td>
    </tr>
    <tr>
        <td>Pavadinimas</td>
        <td>[dct:title](http://purl.org/dc/terms/title)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..n</td>
        <td>-</td>
        <td>Katalogo įrašui suteiktas pavadinimas.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:record_title">E</a></td>
    </tr>
</table>


## Kontrolinė suma

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Kontrolinė suma</td>
                <td>Reikšmė, leidžianti patvirtinti failo turinio autentiškumą.</td>
                <td> - </td>
                <td>[spdx:Checksum](http://spdx.org/rdf/terms#Checksum)</td>
            </tr>
           
        </table>
<br>
 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
            <tr>
        <td>Algoritmas</td>
        <td>[spdx:algorithm](http://spdx.org/rdf/terms#algorithm)</td>
        <td>[spdx:ChecksumAlgorithm](http://spdx.org/rdf/terms#ChecksumAlgorithm)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Algoritmas, naudojamas objekto kontrolinei sumai sukurti.</td>
                <td><a href="https://w3c.github.io/dxwg/dcat/#Property:checksum_algorithm">E</a></td>
    </tr>
    <tr>
        <td>Kontrolinės sumos reikšmė</td>
        <td>[spdx:checksumValue](http://spdx.org/rdf/terms#checksumValue)<br>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Mažosiomis raidėmis užkoduota šešioliktainė skaitmeninė vertė, sukurta naudojant tam tikrą algoritmą.</td>
                <td><a href="https://w3c.github.io/dxwg/dcat/#Property:checksum_checksum_value">E</a></td>
    </tr>
</table>

## Dokumentas

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Dokumentas</td>
                <td>Abstrakti klasė apibūdinanti įvairių tipų dokumentus</td>
                <td></td>
                <td>[foaf:Document](http://xmlns.com/foaf/0.1/Document)</td>
            </tr>
           
        </table>

 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
</table>


## Dažnis

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
             <tr class="data-table__header">
        <td>Dažnis</td>
        <td>Žymimas tam tikrų įvykių dažnumas, pavyzdžiui duomenų atnaujinimo.</td>
        <td> - </td>
        <td><a href="http://purl.org/dc/terms/Frequency">dct:Frequency</a></td>
    </tr>
           
        </table>



## Identifikatorius

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr>
            <td>Identifikatorius</td>
        <td>Identifikatorius tam tikrame kontekste, yra eilutė (angl. string), kuri ir yra identifikatorius;
neprivalomas identifikatoriaus schemos identifikatorius;
neprivalomas identifikatoriaus schemos versijos identifikatorius;
neprivalomas identifikatoriaus schemą valdančios agentūros identifikatorius.
</td>
        <td> - </td>
        <td><a href="http://www.w3.org/ns/adms#Identifier">adms:Identifier</a></td>
    </tr>
           
        </table>
<br>

        <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
            <tr>
        <td>Žymėjimas</td>
        <td>[skos:notation](http://www.w3.org/2004/02/skos/core#notation)<br>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>1..1</td>
        <td>-</td>
        <td>Ši savybė yra eilutė, kuri yra identifikatorius pagal identifikatoriaus schemą, į kurią nurodo jos duomenų tipas.</td>
        <td>P</td>
        </tr>
        </table>


## Rūšis

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:30%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:30%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
          <tr>
        <td>Rūšis</td>
        <td>Pagal vCard specifikaciją, pvz., kontaktinio asmens telefono numeriui ir el. pašto adresui nurodyti.</td>
        <td>Klasė Rūšis yra tėvinė klasė keturių vCard kortelių tipų (Individualus asmuo, Organizacija, Vieta, Grupė).</td>
        <td><a href="http://www.w3.org/2006/vcard/ns#Kind">vcard:Kind</a></td>
    </tr>
           
        </table>


## Lingvistinė sistema

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:30%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
         <tr>
        <td>Lingvistinė sistema</td>
        <td>Komunikacijoje naudojama ženklų, simbolių, garsų, gestų ar taisyklių sistema, pvz. kalba.</td>
        <td> - </td>
        <td><a href="http://purl.org/dc/terms/LinguisticSystem">dct:LinguisticSystem</a></td>
    </tr>
           
        </table>

 


## Vietovė

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:30%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:30%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Vietovė</td>
                <td>Erdvinis regionas arba įvardyta vieta.</td>
                <td>Naudojimo pastaba: gali būti vaizduojama naudojant kontroliuojamąjį žodyną arba geografines koordinates. Pastaruoju atveju rekomenduojama naudoti pagrindinį vietovės žodyną, laikantis GeoDCAT-AP specifikacijoje aprašyto metodo.</td>
                <td>[dct:Location](http://purl.org/dc/terms/Location)</td>
            </tr>
           
        </table>

 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
		  <tr>
        <td>Geografinis ribinis stačiakampis</td>
        <td>[dcat:bbox](http://www.w3.org/ns/dcat#bbox)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo išteklių geografines ribas.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:location_bbox">E</a></td>

    </tr>
    <tr>
        <td>Centroidas</td>
        <td>[dcat:centroid](http://www.w3.org/ns/dcat#centroid)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė nurodo išteklių geografinį centrą (centroidą).</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:location_centroid">E</a></td>
    </tr>
    <tr>
        <td>Geometrija</td>
        <td>[locn:geometry](http://www.w3.org/ns/locn#geometry)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Ši savybė susieja bet kurį išteklių su atitinkama geometrija.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:location_geometry">E</a></td>
    </tr>
</table>


## Medijos tipas

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Medijos tipas</td>
                <td>Medijos tipas, pvz. kompiuterio failo formatas.</td>
                <td></td>
                <td>[dct:MediaType](http://purl.org/dc/terms/MediaType)</td>
            </tr>
           
        </table>



## Laikotarpis

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Laikotarpis</td>
                <td>Laiko intervalas, apibrėžtas pradžios ir pabaigos datomis.</td>
                <td> - </td>
                <td>[dct:PeriodOfTime](http://purl.org/dc/terms/PeriodOfTime)</td>
            </tr>
           
        </table>

 <table class="data-table simple">
         
            <tr class="data-table__header">
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Savybė</th>
                <th class="data-table__header-title--sortable" style="width:10%">Išteklius</th>
                <th class="data-table__header-title--sortable" style="width:10%">Intervalas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Kard</th>
                <th class="data-table__header-title--sortable" style="width:20%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:45%">Aprašymas</th>
                <th class="data-table__header-title--sortable" style="width:5%">Perpanaudojimas</th>
            </tr>
<br></br>
             <tr>
        <td>Pabaigos data</td>
        <td>[dcat:endDate](https://www.w3.org/ns/dcat#endDate)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Laikotarpio pabaigos data.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:period_end_date">E</a></td>
     </tr>
     <tr>
        <td>Pradžios data</td>
        <td>[dcat:startDate](http://www.w3.org/ns/dcat#startDate)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Laikotarpio pradžios data.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:period_start_date">E</a></td>
     </tr>
     <tr>
        <td>Turi pradžią</td>
        <td>[time:hasBeginning](http://www.w3.org/2006/time#hasBeginning)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Periodo arba intervalo pradžios data.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:period_has_beginning">E</a></td>
     </tr>
     <tr>
        <td>Turi pabaigą</td>
        <td>[time:hasEnd](http://www.w3.org/2006/time#hasEnd)</td>
        <td>[rdfs:Literal](http://www.w3.org/2000/01/rdf-schema#Literal)</td>
        <td>0..1</td>
        <td>-</td>
        <td>Periodo arba intervalo pabaigos data.</td>
                <td><a href="https://www.w3.org/TR/vocab-dcat-3/#Property:period_has_end">E</a></td>
      </tr>
     </table>

## Teisių deklaracija

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Teisių deklaracija</td>
                <td>Deklaracija apie intelektinės nuosavybės teises (INT), turimas išteklyje esančiai informacijai arba ištekliui, teisinis dokumentas, suteikiantis oficialų leidimą ką nors daryti su ištekliu, arba deklaracija apie prieigos teises.</td>
                <td> - </td>
                 <td>[dct:RightsStatement](http://purl.org/dc/terms/RightsStatement)</td>
            </tr>
           
        </table>



## Duomenų tvarkytojo deklaracija

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Duomenų tvarkytojo deklaracija</td>
                <td>Šioje klasėje pateikiami bet kokie ištekliaus nuosavybės ir saugojimo pokyčiai nuo jo sukūrimo, kurie yra reikšmingi jo autentiškumui, vientisumui ir aiškinimui. deklaracija apie duomenų rinkinio kilmę.</td>
                <td> - </td>
                <td>[dct:ProvenanceStatement](http://purl.org/dc/terms/ProvenanceStatement)</td>
            </tr>
           
        </table>


## Standartas

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Standartas</td>
                <td>Standartas ar kitaspecifikacija, kurią atitinka duomenų rinkinys ar pateiktis</td>
                <td></td>
                <td>[dct:Standard](http://purl.org/dc/terms/Standard)</td>
            </tr>
           
        </table>


## Kontaktinė informacija

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Kontaktinė informacija</td>
                <td>Šia klase aprašoma kontaktinė informacija</td>
                <td> - </td>
                <td>[schema:ContactPoint](http://schema.org/ContactPoint)</td>
            </tr>
           
        </table>



## Kokybės anotacija

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Kokybės anotacija</td>
                <td>Nurodo kokybės anotacijas, įskaitant įvertinimus, kokybės sertifikatus arba atsiliepimus, kurie gali būti susieti su duomenų rinkiniais arba pateiktimis. Kokybės anotacijose turi būti vienas teiginys oa:motivatedBy su oa:Motyvacija (ir skos:Concept) pavyzdžiu, kuris atspindi kokybės vertinimo tikslą. Šį atvejį apibrėžiame kaip dqv:qualityAssessment.</td>
                <td> - </td>
                <td>[dqv:QualityAnnotation](http://www.w3.org/ns/dqv#QualityAnnotation)</td>
            </tr>
           
        </table>




## Kokybės matavimas

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Kokybės matavimas</td>
                <td>Šia klase apibrėžiamos galimas kokybės vertinimas pagal specifinius kokybės vertinimo kriterijus</td>
                <td> - </td>
                <td>[dqv:QualityMeasurement](http://www.w3.org/ns/dqv#QualityMeasurement)</td>
            </tr>
           
        </table>


## Veikla

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Veikla</td>
                <td>Veikla yra veiksmai, kurie vyksta per tam tikrą laikotarpį ir daro įtaką ištekliams; tai gali apimti duomenų ar kitų išteklių naudojimą, apdorojimą, transformavimą, modifikavimą, perkėlimą, naudojimą ar generavimą</td>
                <td> - </td>
                <td>[prov:Activity](http://www.w3.org/ns/prov#Activity)</td>
            </tr>
           
        </table>



## Adresas

 <table class="data-table simple">
            <tr >
                <th class="data-table__header-title--sortable data-table__header-title--sortable-active" style="width:12%">Klasė</th>
                <th class="data-table__header-title--sortable" style="width:50%">Aprašas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Kontekstas</th>
                <th class="data-table__header-title--sortable" style="width:12%">Išteklius</th>
            </tr>
            <tr class="data-table__header">
                <td>Adresas</td>
                <td>„Adreso atvaizdavimas“, kaip konceptualiai apibrėžiamas INSPIRE adreso atstovavimo duomenų tipas. </td>
                <td></td>
                <td>[locn:Address](http://www.w3.org/ns/locn#Address)</td>
            </tr>
           
        </table>



# Didelės vertės duomenų rinkinians naudojamos (DCAT-AP-HVD) klasės ir savybės

Didelės vertės duomenų rinkinių apibrėžimas atsirado iš poreikio identifikuoti svarbiausius duomenis pavyzdžiui:
<ul>
    <li>geografiniai duomenys</li>
    <li>žemės stebėjimo ir aplinkos duomenys</li>
    <li>meteorologiniai duomenys</li>
    <li>statistiniai duomenys</li>
    <li>įmonių ir jų savininkų duomenys</li>
    <li>mobilumo duomenys</li>
</ul>
Šie duomenys turi didžiausią potencialą daryti įtaką svarbiausioms Europos Komisijos įvardintoms sritims. Tokių duomenų atvėrimas ir pakartotinis panaudojimas sukuria didelę pridėtinę vertę, bet tuo pačiu reikalauja papildomų taisyklių, reglamentuojančių jų prieinamumą, sąveikumą ir panaudojimą. Atsižvelgiant į tai, kad DCAT-AP plėtinys negali pilnai patenkinti didelės vertės duomenų rinkinių kokybės, patikimumo bei atvirumo reikalavimų, buvo pradėtas vystyti DCAT-AP HVD plėtinys, remiantis gairėmis, kurios pateiktos Didelės vertės duomenų rinkinio įgyvendinimo reglamente . Atitinkamai šis plėtinys yra adaptuojamas ir DCAT-AP-LT, pakeičiant LegalResource išteklių į atributą pagal ELI:LegalResource pavadinimu id_local.

## Bendrosios didelės vertės duomenų rinkinių savybės

Didelės vertės duomenų rinkiniai pasižymi specifiniais techniniais ir teisiniais reikalavimais. Šiems duomenų rinkiniams taikomi šie bendri reikalavimai:
<ul>
    <li>atvirosios duomenų licencijos;</li>
    <li>viešai prieinamos dokumentacijos;</li>
    <li>mašininio skaitomumo užtikrinimas;</li>
    <li>galimybė (jei tai įmanoma) parsisiųsti visus pageidaujamus duomenis vienu kartu;</li>
    <li>galimybė gauti duomenis naudojant API sąsajas;</li>
    <li>nemokama prieiga ir gavimas;</li>
    <li>išsamūs metaduomenų aprašai.</li>
</ul>
Atsižvelgiant į šias savybes ir, atitinkamai, iš to išplaukiančius reikalavimus, DCAT-AP-LT modelyje atsiranda poreikis taikyti papildomas, modifikuotas ar sugriežtintas metaduomenų modelio taisykles didelės vertės duomenų rinkiniams. Šios taisyklės apima DCAT-AP klases papildančias savybes ar griežtesnį esamų savybių privalomumo taikymą ir yra apibrėžtos <a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/">DCAT-AP-HVD</a> priede. 

## Katalogas
<dl>
    <dt>Apibrėžimas</dt>
    <dd>Katalogas arba saugykla, kurioje yra aprašomi duomenų rinkiniai arba duomenų paslaugos.</dd>
    <dt>DCAT nuoroda</dt>
    <dd><a href="https://w3c.github.io/dxwg/dcat/#Class:Catalog">Nuoroda</a></dd>
    <dt>Savybės</dt>
    <dd>Apibrėžiamos šios šio objekto ypatybės: <a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Catalogue.dataset">duomenų rinkinys,</a> 
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Catalogue.record">įrašas,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Catalogue.service">paslauga.</a>
	</dd>
    <dd>
<table>
  <thead>
    <tr>
      <th>Savybė</th>
      <th>Intervalas</th>
      <th>Kard</th>
      <th>Apibrėžimas</th>
      <th>Naudojimas</th>
      <th>Perpanaudojimas</th>
    </tr>
  </thead>
<br></br>
  <tbody>
    <tr>
      <td>[duomenų rinkinys](http://www.w3.org/ns/dcat#dataset)</td>
      <td>[Dataset](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Dataset)</td>
      <td>0..*</td>
      <td>Duomenų rinkinys, kuris yra dalis katalogo.</td>
      <td>Kadangi tuščių katalogų paprastai yra problemų požymis, šią savybę reikėtų derinti su kita savybe „service“, kad būtų įgyvendinta tuščio katalogo patikra.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Catalogue.dataset">A</a></td>
    </tr>
    <tr>
      <td>[įrašas](http://www.w3.org/ns/dcat#record)</td>
      <td>[Catalogue Record](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#CatalogueRecord)</td>
      <td>0..*</td>
      <td>Katalogo įrašas, kuris yra dalis katalogo.</td>
      <td></td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Catalogue.record">A</a></td>
    </tr>
    <tr>
      <td>[paslauga](http://www.w3.org/ns/dcat#service)</td>
      <td>[Data Service](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService)</td>
      <td>0..*</td>
      <td>Svetainė arba galutinis taškas (duomenų paslauga), kuris yra išvardytas kataloge.</td>
      <td>Kadangi tuščių katalogų paprastai yra problemų požymis, šią savybę reikėtų derinti su ankstesne savybe „dataset“, kad būtų įgyvendinta tuščio katalogo patikra.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Catalogue.service">A</a></td>
    </tr>
  </tbody>
</table>
  </dd>
</dl>


## Katalogo įrašas
<dl>
    <dt>Apibrėžimas</dt>
    <dd>Duomenų rinkinio įrašo kataloge aprašymas.</dd>
    <dt>DCAT nuoroda</dt>
    <dd><a href="https://w3c.github.io/dxwg/dcat/#Class:Catalog_Record">Nuoroda</a></dd>
    <dt>Savybės</dt>
    <dd>Apibrėžiamos šios šio objekto ypatybės: <a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#CatalogueRecord.primarytopic">pagrindinė tema,</a>
	</dd>
    <dd>
<table>
  <thead>
    <tr>
      <th>Savybė</th>
      <th>Intervalas</th>
      <th>Kard</th>
      <th>Apibrėžimas</th>
      <th>Naudojimas</th>
      <th>Perpanaudojimas</th>
    </tr>
  </thead>
<br></br>
  <tbody>
    <tr>
      <td>[pagrindinė tema](http://xmlns.com/foaf/0.1/primaryTopic)</td>
      <td>[Catalogued Resource](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#CataloguedResource)</td>
      <td>1</td>
      <td>Nuoroda į aprašytąjį duomenų rinkinį, duomenų paslaugą arba katalogą.</td>
      <td>Katalogo įrašas nurodys vieną subjektą kataloge. Tai gali būti arba duomenų rinkinys, arba duomenų paslauga. Siekiant užtikrinti neambicingą kardinalumo skaitymą, diapazonas nustatomas kaip Kataloguojamas išteklius. Tačiau šio diapazono tikslas nėra reikalauti eksplicitiškai naudoti klasę Kataloguotas įrašas. Kaip abstrakti klasė, turėtų būti naudojama antrinė klasė.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#CatalogueRecord.primarytopic">A</a></td>
    </tr>
  </tbody>
</table>
  </dd>
</dl>

## Katalogo resursas
<dl>
    <dt>Apibrėžimas</dt>
    <dd>Šaltinis, kurį paskelbė arba kuravo vienas agentas.</dd>
    <dt>DCAT nuoroda</dt>
    <dd><a href="https://w3c.github.io/dxwg/dcat/#Class:Resource">Nuoroda</a></dd>
    <dt>Naudojimo pastaba</dt>
    <dd>Ši klasė yra laikoma kaip abstrakti sąvoka.</dd>
    <dt>Savybės</dt>
    <dd>Ši specifikacija nenustato jokių papildomų reikalavimų šio objekto savybėms.</dd>
    <dd>
  </dd>
</dl>
## Duomenų paslauga
<dl>
    <dt>Apibrėžimas</dt>
    <dd>Operacijų rinkinys, suteikiantis prieigą prie vieno ar daugiau duomenų rinkinių arba duomenų apdorojimo funkcijų.</dd>
    <dt>DCAT nuoroda</dt>
    <dd><a href="https://w3c.github.io/dxwg/dcat/#Class:Data_Service">Nuoroda</a></dd>
    <dt>Šios klasės poklasė</dt>
    <dd><a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#CataloguedResource">Katalogo resursas</a></dd>
    <dt>Savybės</dt>
    <dd>Apibrėžiamos šios šio objekto ypatybės: <a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.applicablelegislation">teisinis pagrindas,</a> 
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.contactpoint">kontaktas,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.documentation">dokumentacija,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.endpointdescription">prieigos taško aprašymas,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.endpointURL">prieigos taško URL,</a>	
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.HVDcategory">didelės vertės duomenų rinkinio kategorija,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.licence">licencija,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.rights">teisės,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.servesdataset">pateikia duomenų rinkinį.</a>
	</dd>
    <dd>
<table>
  <thead>
    <tr>
      <th>Savybė</th>
      <th>Intervalas</th>
      <th>Kard</th>
      <th>Apibrėžimas</th>
      <th>Naudojimas</th>
      <th>Perpanaudojimas</th>
    </tr>
  </thead>
<br></br>
  <tbody>
    <tr>
      <td>[teisinis pagrindas](http://data.europa.eu/r5r/applicableLegislation)</td>
      <td>[Legal Resource](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#LegalResource)</td>
      <td>1..*</td>
      <td>Teisės aktai, kurie įpareigoja kurti ar valdyti duomenų paslaugą.</td>
      <td>HVD atveju reikšmė PRIVALO apimti ELI http://data.europa.eu/eli/reg_impl/2023/138/oj. Kadangi į išteklių gali būti taikomi keli teisės aktai, maksimalus kardinalumas nėra ribojamas.</td>
      <td>P</td>
    </tr>
    <tr>
      <td>[kontaktas](http://www.w3.org/ns/dcat#contactPoint)</td>
      <td>[Kind](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Kind)</td>
      <td>1..*</td>
      <td>Kontaktinė informacija, kurią galima naudoti siunčiant pastabas apie duomenų paslaugą.</td>
      <td>3.4 straipsnis reikalauja paskirti kontaktinį tašką API.</td>
      <td>P</td>
    </tr>
    <tr>
      <td>[dokumentacija](http://xmlns.com/foaf/0.1/Page)</td>
      <td>[Document](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Document)</td>
      <td>1..*</td>
      <td>Puslapis, kuriame pateikiama papildoma informacija apie duomenų paslaugą.</td>
      <td>Paslaugų kokybė apima plačią aspektų spektrą. HVD reglamentas nenustato jokių privalomų temų. Todėl paslaugų kokybės informacija laikoma bendrosios duomenų paslaugos dokumentacijos dalimi.</td>
      <td>P</td>
    </tr>
    <tr>
      <td>[prieigos taško aprašymas](http://www.w3.org/ns/dcat#endpointDescription)</td>
      <td>[Resource](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Resource)</td>
      <td>0..*</td>
      <td>Aprašymas paslaugų, prieinamų per galutinius taškus, įskaitant jų operacijas, parametrus ir t.t.</td>
      <td>Savybė pateikia konkrečias faktinių galutinių taškų detales, o dct:conformsTo naudojama nurodyti bendrąjį standartą ar specifikaciją, kurią įgyvendina galutiniai taškai. 3.3 straipsnis reikalauja pateikti API dokumentaciją Sąjungos arba tarptautiniu mastu pripažintu atviru, žmogui skaitomu ir mašinai skaitomu formatu.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DataService.endpointdescription">E</a></td>
    </tr>
    <tr>
      <td>[prieigos taško URL](http://www.w3.org/ns/dcat#endpointURL)</td>
      <td>[Resource](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Resource)</td>
      <td>1..*</td>
      <td>Pagrindinė paslaugos vieta arba pirminis galutinis taškas (IRI).</td>
      <td>Galutinio taško URL TURĖTŲ būti pastovus. Tai reiškia, kad leidėjai turėtų daryti viską, kas įmanoma, kad išlaikytų reikšmę stabilia ir egzistuojančia.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DataService.endpointURL">E</a></td>
    </tr>
    <tr>
      <td>[didelės vertės duomenų rinkinio kategorija](http://data.europa.eu/r5r/hvdCategory)</td>
      <td>[Concept](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Concept)</td>
      <td>1..*</td>
      <td>HVD kategorija, kuriai priklauso ši duomenų paslauga.</td>
      <td>-</td>
      <td>P</td>
    </tr>
    <tr>
      <td>[licencija](http://purl.org/dc/terms/license)</td>
      <td>[Licence Document](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#LicenceDocument)</td>
      <td>0..1</td>
      <td>Licencija, pagal kurią teikiama duomenų paslauga.</td>
      <td>3.3 straipsnis nurodo, kad turi būti pateiktos naudojimo sąlygos. Pagal DCAT-AP HVD teisinės informacijos gaires tai įgyvendinama pirmenybė teikiant licenciją. Kaip alternatyvą gali būti naudojamos teisės.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DataService.licence">E</a></td>
    </tr>
    <tr>
      <td>[teisės](http://purl.org/dc/terms/rights)</td>
      <td>[Rights statement](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Rightsstatement)</td>
      <td>0..*</td>
      <td>Deklaracija, kuriame nurodomos su platinimu susijusios teisės.</td>
      <td>3.3 straipsnis nurodo, kad turi būti pateiktos naudojimo sąlygos. Pagal DCAT-AP HVD teisinės informacijos gaires tai įgyvendinama pirmenybė teikiant licenciją. Kaip alternatyvą gali būti naudojamos teisės.</td>
      <td>P</td>
    </tr>
    <tr>
      <td>[pateikia duomenų rinkinį](http://www.w3.org/ns/dcat#servesDataset)</td>
      <td>[Dataset](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Dataset)</td>
      <td>1..*</td>
      <td>Ši savybė nurodo duomenų rinkinį, kurį ši duomenų paslauga gali platinti.</td>
      <td>API HVD kontekste nėra atskiras išteklius. Jis naudojamas atverti HVD duomenų rinkinius. Todėl kiekviena duomenų paslauga bent jau yra glaudžiai susijusi su duomenų rinkiniu.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DataService.servesdataset">E</a></td>
    </tr>
  </tbody>
</table>
  </dd>
</dl>

## Duomenų rinkinys

<dl>
    <dt>Apibrėžimas</dt>
    <dd>Konceptualus objektas, atitinkantis paskelbtą informaciją.</dd>
    <dt>DCAT nuoroda</dt>
    <dd><a href="https://w3c.github.io/dxwg/dcat/#Class:Dataset">Nuoroda</a></dd>
    <dt>Šios klasės poklasė</dt>
    <dd><a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#CataloguedResource">Katalogo resursas</a></dd>
    <dt>Savybės</dt>
<dd>Apibrėžiamos šios šio objekto ypatybės: <a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.applicablelegislation">teisinis pagrindas,</a> 
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Dataset.conformsto">taikymo profilis,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.contactpoint">kontaktas,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Dataset.datasetdistribution">duomenų rinkinio pateikimas,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.HVDcategory">didelės vertės duomenų rinkinio kategorija.</a>
	</dd>
    <dd>
<table>
  <thead>
    <tr>
          <th>Savybė</th>
      <th>Intervalas</th>
      <th>Kard</th>
      <th>Apibrėžimas</th>
      <th>Naudojimas</th>
      <th>Perpanaudojimas</th>
    </tr>
  </thead>
<br></br>
  <tbody>
    <tr>
      <td>[teisinis pagrindas](http://data.europa.eu/r5r/applicableLegislation)</td>
      <td>[Legal Resource](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#LegalResource)</td>
      <td>1..*</td>
      <td>Teisės aktai, kurie įpareigoja kurti ar valdyti duomenų rinkinį.</td>
      <td>HVD atveju reikšmė privalo apimti ELI http://data.europa.eu/eli/reg_impl/2023/138/oj. Kadangi į išteklių gali būti taikomi keli teisės aktai, maksimalus kardinalumas nėra ribojamas.</td>
      <td>P</td>
    </tr>
    <tr>
      <td>[atitinka](http://purl.org/dc/terms/conformsTo)</td>
      <td>[Standard](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Standard)</td>
      <td>0..*</td>
      <td>Įgyvendinimo taisyklė ar kita specifikacija.</td>
      <td>Pateikta informacija turėtų leisti patikrinti, ar yra tenkinami išsamūs HVD informacijos reikalavimai. Daugiau naudojimo pasiūlymų žr. skyriuje apie konkrečius duomenų reikalavimus.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.conformsto">A</a></td>
    </tr>
    <tr>
      <td>[contact point](http://www.w3.org/ns/dcat#contactPoint)</td>
      <td>[Kind](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Kind)</td>
      <td>0..*</td>
      <td>Kontaktinė informacija, kurią galima naudoti siunčiant pastabas apie duomenų rinkinį.</td>
      <td>-</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.contactpoint">A</a></td>
    </tr>
    <tr>
      <td>[duomenų rinkinio pateiktis](http://www.w3.org/ns/dcat#distribution)</td>
      <td>[Distribution](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Distribution)</td>
      <td>1..*</td>
      <td>Prieinama duomenų rinkinio pateiktis.</td>
      <td>HVD IR yra esamų duomenų rinkinių kokybės gerinimas. Tikimasi, kad HVD duomenų rinkiniai yra viešai ir atvirai prieinami. Todėl tikimasi, kad pateiktis bus pateikta. (3.1 straipsnis)</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.datasetdistribution">A</a></td>
    </tr>
    <tr>
      <td>[didelės vertės duomenų rinkinio kategorija](http://data.europa.eu/r5r/hvdCategory)</td>
      <td>[Concept](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Concept)</td>
      <td>1..*</td>
      <td>HVD kategorija, kuriai priklauso šis duomenų rinkinys.</td>
      <td>-</td>
      <td>P</td>
    </tr>
  </tbody>
</table>
  </dd>
</dl>

## Pateiktis
<dl>
    <dt>Apibrėžimas</dt>
    <dd>Katalogas arba saugykla, kurioje yra aprašomi duomenų rinkiniai arba duomenų paslaugos.</dd>
    <dt>DCAT nuoroda</dt>
    <dd><a href="https://w3c.github.io/dxwg/dcat/#Class:Distribution">Nuoroda</a></dd>
    <dt>Naudojimo pastaba</dt>
    <dd>Masiniai atsisiuntimai turi būti koduojami kaip pateikimas.</dd>
    <dt>Savybės</dt>
    <dd>Apibrėžiamos šios šio objekto ypatybės: <a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Distribution.accessservice">prieigos paslauga,</a> 
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Distribution.accessURL">prieigos URL,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Distribution.applicablelegislation">teisinis pagrindas,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Distribution.licence">licencija,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Distribution.linkedschemas">susijusi schema,</a>
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Distribution.rights">teisės.</a>
	</dd>
    <dd>
<table>
  <thead>
    <tr>
     <th>Savybė</th>
      <th>Intervalas</th>
      <th>Kard</th>
      <th>Apibrėžimas</th>
      <th>Naudojimas</th>
      <th>Perpanaudojimas</th>
    </tr>
  </thead>
<br></br>
  <tbody>
    <tr>
      <td>[prieigos paslauga](http://www.w3.org/ns/dcat#accessService)</td>
      <td>[Data Service](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService)</td>
      <td>0..*</td>
      <td>Duomenų paslauga, suteikianti prieigą prie duomenų rinkinio platinimo.</td>
      <td>-</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.accessservice">A</a></td>
    </tr>
    <tr>
      <td>[prieigos URL](http://www.w3.org/ns/dcat#accessURL)</td>
      <td>[Resource](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Resource)</td>
      <td>1..*</td>
      <td>URL, suteikiantis prieigą prie duomenų rinkinio pateikties.</td>
      <td>Išteklius prieigos URL adrese turėtų apimti informaciją, kaip gauti duomenų rinkinį. Pagal DCAT gaires pageidautina taip pat nustatyti downloadURL savybę, jei URL yra nuoroda į atsisiunčiamą išteklių.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.accessURL">A</a></td>
    </tr>
    <tr>
      <td>[teisinis pagrindas](http://data.europa.eu/r5r/applicableLegislation)</td>
      <td>[Legal Resource](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#LegalResource)</td>
      <td>1..*</td>
      <td>Teisės aktai, kurie įpareigoja kurti ar valdyti platinimą.</td>
      <td>HVD atveju reikšmė privalo apimti ELI http://data.europa.eu/eli/reg_impl/2023/138/oj. Kadangi į išteklių gali būti taikomi keli teisės aktai, maksimalus kardinalumas nėra ribojamas.</td>
      <td>P</td>
    </tr>
    <tr>
      <td>[licencija](http://purl.org/dc/terms/license)</td>
      <td>[Licence Document](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#LicenceDocument)</td>
      <td>0..1</td>
      <td>Licencija, pagal kurią pateiktis yra prieinama.</td>
      <td>4.3 straipsnis nurodo, kad aukštos vertės duomenų rinkiniai turėtų būti prieinami naudojimui. Pagal DCAT-AP HVD teisinės informacijos gaires tai įgyvendinama pirmenybė teikiant licenciją. Kaip alternatyvą gali būti naudojamos teisės.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.licence">E</a></td>
    </tr>
    <tr>
      <td>[susijusi schema](http://purl.org/dc/terms/conformsTo)</td>
      <td>[Standard](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Standard)</td>
      <td>0..*</td>
      <td>Nustatyta schema, kurią atitinka aprašyta pateiktis.</td>
      <td>Pateikta informacija turėtų leisti patikrinti, ar yra tenkinami išsamūs HVD informacijos reikalavimai. Daugiau naudojimo pasiūlymų žr. skyriuje apie konkrečius duomenų reikalavimus.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.linkedschemas">A</a></td>
    </tr>
    <tr>
      <td>[teisės](http://purl.org/dc/terms/rights)</td>
      <td>[Rights statement](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Rightsstatement)</td>
      <td>0..*</td>
      <td>Deklaracija, kurioje nurodomos su platinimu susijusios teisės.</td>
      <td>4.3 straipsnis nurodo, kad aukštos vertės duomenų rinkiniai turėtų būti prieinami naudojimui. Pagal DCAT-AP HVD teisinės informacijos gaires tai įgyvendinama pirmenybė teikiant licenciją. Kaip alternatyvą gali būti naudojamos teisės.</td>
      <td><a href="https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.rights">E</a></td>
    </tr>
  </tbody>
</table>
  </dd>
</dl>
## Rūšis
<dl>
    <dt>Apibrėžimas</dt>
    <dd>Aprašymas pagal "vCard" specifikaciją, pvz., nurodant kontaktinio punkto telefono numerį ir el. pašto adresą.</dd>
    <dt>Naudojimo pastaba</dt>
    <dd>Rekomenduojama pateikti bent el. laišką arba kontaktinę formą iš, pvz., aptarnavimo centro.</dd>
    <dt>Savybės</dt>
    <dd>Apibrėžiamos šios šio objekto ypatybės: <a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Kind.contactpage">kontaktas</a> 
	<a href="https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Kind.email">el. paštas.</a>
	</dd>
    <dd>
<table>
  <thead>
    <tr>
<th>Savybė</th>
      <th>Intervalas</th>
      <th>Kard</th>
      <th>Apibrėžimas</th>
      <th>Naudojimas</th>
      <th>Perpanaudojimas</th>
    </tr>
  </thead>
<br></br>
  <tbody>
    <tr>
      <td>[kontaktas](http://www.w3.org/2006/vcard/ns#hasURL)</td>
      <td>[Resource](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Resource)</td>
      <td>0..1</td>
      <td>Tinklalapis, kuris leidžia užmegzti kontaktą (pvz., per internetinę formą) arba informacija, kaip susisiekti.</td>
      <td>-</td>
      <td>P</td>
    </tr>
    <tr>
      <td>[el.paštas](http://www.w3.org/2006/vcard/ns#hasEmail)</td>
      <td>[Resource](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#Resource)</td>
      <td>0..1</td>
      <td>El. pašto adresas, per kurį galima užmegzti kontaktą.</td>
      <td>-</td>
      <td>P</td>
    </tr>
  </tbody>
</table>
  </dd>
</dl>
## Licencijos dokumentas
<dl>
    <dt>Apibrėžimas</dt>
    <dd>Teisinis dokumentas, suteikiantis oficialų leidimą ką nors daryti su ištekliais.</dd>
    <dt>Naudojimo pastaba</dt>
    <dd>Pagal HVD yra reikalaujama, kad licencija būtų pateikiama kompiuterio skaitomu būdu. Minimalių duomenų modelis licencijos dokumentui apibūdinti yra už šios specifikacijos ribų.</dd>
    <dt>Savybės</dt>
    <dd>Ši specifikacija nenustato jokių papildomų reikalavimų šio objekto ypatybėms.</dd>
    <dd>
  </dd>
</dl>
